-- No network requests. All test accounts, sources, permissions and attempts roll back.
begin;
do $$
declare owner_uid uuid:=gen_random_uuid(); other_uid uuid:=gen_random_uuid(); sid uuid; vid uuid; second_vid uuid;
  s jsonb; v jsonb; j jsonb; a jsonb; dispatch jsonb; a_request uuid:=gen_random_uuid(); denied boolean;
begin
  insert into auth.users(id,aud,role,email) values(owner_uid,'authenticated','authenticated',owner_uid::text||'@example.invalid'),(other_uid,'authenticated','authenticated',other_uid::text||'@example.invalid');
  perform set_config('request.jwt.claim.sub',owner_uid::text,true);
  set local role authenticated;
  s:=public.unsite_command('create_space',jsonb_build_object('name','AI consent fixture','kind','person','request_id',gen_random_uuid()));sid:=(s->>'id')::uuid;
  v:=public.unsite_command('source_intake',jsonb_build_object('space_id',sid,'title','Private fixture','kind','text','text_content','Private source text selected only by its owner.','request_id',gen_random_uuid()));vid:=(v->>'id')::uuid;
  denied:=false;begin perform public.unsite_ai_command('prepare_source',jsonb_build_object('space_id',sid,'version_id',vid,'approved',false,'disclosure_version','openai-source-preparation-2026-09-05','request_id',a_request));exception when raise_exception then denied:=SQLERRM='Review the AI disclosure';end;assert denied,'unchecked consent rejected';
  denied:=false;begin perform public.unsite_ai_command('prepare_source',jsonb_build_object('space_id',sid,'version_id',vid,'approved',true,'disclosure_version','obsolete','request_id',a_request));exception when raise_exception then denied:=SQLERRM='Review the AI disclosure';end;assert denied,'wrong disclosure rejected';
  reset role;
  set local role service_role;
  j:=public.unsite_claim_job();
  perform public.unsite_job_result((j->>'id')::uuid,(j->>'lease_token')::uuid,'{"mode":"parsed","text":"Private source text selected only by its owner.","hash":"fixture","chunks":1}'::jsonb);
  dispatch:=public.unsite_ai_dispatch((j->>'id')::uuid,(j->>'lease_token')::uuid,'test-model');assert dispatch->>'reason'='AI_APPROVAL_REQUIRED','unapproved version must not dispatch';
  assert (select count(*) from public.unsite_ai_attempts where space_id=sid)=0,'no consent creates no provider attempt';
  reset role;
  perform set_config('request.jwt.claim.sub',owner_uid::text,true);
  set local role authenticated;
  a:=public.unsite_ai_command('prepare_source',jsonb_build_object('space_id',sid,'version_id',vid,'approved',true,'disclosure_version','openai-source-preparation-2026-09-05','request_id',a_request));
  assert public.unsite_ai_command('prepare_source',jsonb_build_object('space_id',sid,'version_id',vid,'approved',true,'disclosure_version','openai-source-preparation-2026-09-05','request_id',a_request))->>'id'=a->>'id','authorization retry is idempotent';
  perform set_config('request.jwt.claim.sub',other_uid::text,true);
  assert (select count(*) from public.unsite_ai_authorizations where space_id=sid)=0,'consent is tenant isolated';
  denied:=false;begin perform public.unsite_ai_command('stop_preparation',jsonb_build_object('space_id',sid,'version_id',vid));exception when insufficient_privilege then denied:=true;end;assert denied,'another customer cannot revoke consent';
  denied:=false;begin perform public.unsite_ai_dispatch((j->>'id')::uuid,(j->>'lease_token')::uuid,'test-model');exception when insufficient_privilege then denied:=true;end;assert denied,'customer cannot invoke internal provider dispatch';
  reset role;
  set local role service_role;
  dispatch:=public.unsite_ai_dispatch((j->>'id')::uuid,(j->>'lease_token')::uuid,'test-model');assert (dispatch->>'allowed')::boolean,'owner authorization permits dispatch';
  assert public.unsite_ai_dispatch((j->>'id')::uuid,(j->>'lease_token')::uuid,'test-model')->>'reason'='ALREADY_DISPATCHED','one provider request per lease';
  assert (select count(*) from public.unsite_ai_attempts where space_id=sid)=1,'duplicate dispatch consumes no second reservation';
  reset role;
  perform set_config('request.jwt.claim.sub',owner_uid::text,true);
  set local role authenticated;
  perform public.unsite_ai_command('stop_preparation',jsonb_build_object('space_id',sid,'version_id',vid));
  assert (select revoked_at is not null from public.unsite_ai_authorizations where id=(a->>'id')::uuid),'revocation recorded';
  denied:=false;begin perform public.unsite_ai_command('prepare_source',jsonb_build_object('space_id',sid,'version_id',vid,'approved',true,'disclosure_version','openai-source-preparation-2026-09-05','request_id',a_request));exception when raise_exception then denied:=SQLERRM='Record changed';end;assert denied,'replayed old approval cannot undo revocation';
  reset role;
  set local role service_role;
  perform public.unsite_ai_finish((dispatch->>'dispatch_id')::uuid,'succeeded','fixture-response',10,12);
  assert not public.unsite_job_result((j->>'id')::uuid,(j->>'lease_token')::uuid,jsonb_build_object('mode','chunk','cursor',0,'dispatch_id',dispatch->>'dispatch_id','candidates','[]'::jsonb)),'revocation fences late output';
  assert public.unsite_ai_dispatch((j->>'id')::uuid,(j->>'lease_token')::uuid,'test-model')->>'reason'='STALE_LEASE','stopped job cannot dispatch';
  reset role;
  perform set_config('request.jwt.claim.sub',owner_uid::text,true);
  set local role authenticated;
  perform public.unsite_ai_command('prepare_source',jsonb_build_object('space_id',sid,'version_id',vid,'approved',true,'disclosure_version','openai-source-preparation-2026-09-05','request_id',gen_random_uuid()));
  v:=public.unsite_command('source_intake',jsonb_build_object('space_id',sid,'source_id',v->>'source_id','title','Private fixture','kind','text','text_content','A changed source version needs its own approval.','request_id',gen_random_uuid()));second_vid:=(v->>'id')::uuid;
  assert not exists(select 1 from public.unsite_ai_authorizations where source_version_id=second_vid),'new version does not inherit approval';
  perform public.unsite_command('cancel_job',jsonb_build_object('space_id',sid,'job_id',(select id from public.unsite_jobs where source_version_id=second_vid)));
  reset role;
  set local role service_role;
  -- The earlier job is ordered first and has a saved parsing checkpoint.
  j:=public.unsite_claim_job();assert (j->>'source_version_id')::uuid=vid,'resume original job';
  dispatch:=public.unsite_ai_dispatch((j->>'id')::uuid,(j->>'lease_token')::uuid,'test-model');assert (dispatch->>'allowed')::boolean,'fresh explicit approval can resume';
  update public.unsite_jobs set leased_until=now()-interval '1 minute' where id=(j->>'id')::uuid;
  perform public.unsite_claim_job();
  assert (select status from public.unsite_jobs where id=(j->>'id')::uuid)='blocked','expired provider request must pause';
  assert (select error_code from public.unsite_jobs where id=(j->>'id')::uuid)='PROVIDER_UNCERTAIN','ambiguous provider result must require review';
  assert (select status from public.unsite_ai_attempts where id=(dispatch->>'dispatch_id')::uuid)='uncertain','ambiguous attempt recorded';
  reset role;
end $$;
rollback;
select 'PASS: explicit version consent, cross-account isolation, replay protection, dispatch idempotency, revoked-result fencing, and ambiguous-charge recovery' as result;
