-- Run only after collection-coordination.sql is applied. No provider/network calls.
-- Generated accounts, evidence, tasks, reservations and publications all roll back.
begin;
do $$
declare uid uuid:=gen_random_uuid(); outsider uuid:=gen_random_uuid();sid uuid;vid uuid;rid uuid;recid uuid;cid uuid;lease uuid;
  s jsonb;source jsonb;j jsonb;r jsonb;t jsonb;dispatch jsonb;segment jsonb;item jsonb;curation jsonb;verification jsonb;request_id uuid:=gen_random_uuid();denied boolean;extract_id text;curate_id uuid;
  context jsonb:='{"summary":"A story told by Mira.","aliases":[],"topics":["Memory"],"status":"unspecified","as_of":null,"type_label":"Fictional scene","framing":"fiction","attribution":"Mira, the narrator"}';
  passage text:='In this story Mira remembers an orchard made of glass. The narrator speaks of imaginary trees.';
begin
  insert into auth.users(id,aud,role,email) values(uid,'authenticated','authenticated',uid||'@example.invalid'),(outsider,'authenticated','authenticated',outsider||'@example.invalid');
  perform set_config('request.jwt.claim.sub',uid::text,true);set local role authenticated;
  s:=public.unsite_command('create_space',jsonb_build_object('name','Collection fixture','kind','collection','request_id',gen_random_uuid()));sid:=(s->>'id')::uuid;
  source:=public.unsite_command('source_intake',jsonb_build_object('space_id',sid,'title','Fiction manuscript','kind','text','text_content',passage,'request_id',gen_random_uuid()));vid:=(source->>'id')::uuid;
  s:=public.unsite_command('create_record',jsonb_build_object('space_id',sid,'request_id',gen_random_uuid(),'title','Glass orchard','kind','general','text',passage,'fields','{"real_event":false,"fee":0,"unknown":null}'::jsonb,'context',context));recid:=(s->>'id')::uuid;
  denied:=false;begin perform public.unsite_collection_command('start_collection_run',jsonb_build_object('space_id',sid,'goal','Understand this story','version_ids',jsonb_build_array(vid),'max_requests',10,'approved',false,'disclosure_version','openai-collection-preparation-2026-09-05','request_id',request_id));exception when raise_exception then denied:=SQLERRM='Review the collection AI disclosure';end;assert denied,'run-level approval is mandatory';
  r:=public.unsite_collection_command('start_collection_run',jsonb_build_object('space_id',sid,'goal','Understand this story','version_ids',jsonb_build_array(vid),'max_requests',10,'approved',true,'disclosure_version','openai-collection-preparation-2026-09-05','request_id',request_id));rid:=(r->>'id')::uuid;
  assert public.unsite_collection_command('start_collection_run',jsonb_build_object('space_id',sid,'goal','Understand this story','version_ids',jsonb_build_array(vid),'max_requests',10,'approved',true,'disclosure_version','openai-collection-preparation-2026-09-05','request_id',request_id))->>'id'=r->>'id','start is idempotent';
  assert (select count(*) from public.unsite_ai_authorizations where source_version_id=vid)=0,'collection consent never grants separate source preparation';
  perform set_config('request.jwt.claim.sub',outsider::text,true);
  assert (select count(*) from public.unsite_collection_runs where space_id=sid)=0,'runs are tenant isolated';
  assert public.unsite_collection_overview(sid)='[]'::jsonb,'summaries are tenant isolated';
  denied:=false;begin perform public.unsite_collection_command('cancel_collection_run',jsonb_build_object('space_id',sid,'run_id',rid));exception when insufficient_privilege then denied:=true;end;assert denied,'outsider cannot stop a run';
  denied:=false;begin perform public.unsite_claim_collection_task();exception when insufficient_privilege then denied:=true;end;assert denied,'customer cannot claim internal tasks';
  reset role;set local role service_role;
  assert public.unsite_claim_collection_task() is null,'run waits for parsing';
  j:=public.unsite_claim_job();assert (j->>'source_version_id')::uuid=vid,'source fixture was claimed';
  assert public.unsite_job_result((j->>'id')::uuid,(j->>'lease_token')::uuid,jsonb_build_object('mode','parsed','text',passage,'hash','fixture','chunks',1));
  select to_jsonb(e) into segment from public.unsite_evidence_segments e where source_version_id=vid;
  assert segment->>'text'=passage and (segment->>'start_char')::integer=0,'canonical segment preserves text and offsets';
  denied:=false;begin update public.unsite_source_versions set extracted_text='Mutated source text' where id=vid;exception when raise_exception then denied:=true;end;assert denied,'parsed source versions are immutable';
  t:=public.unsite_claim_collection_task();assert t->>'stage'='extract';extract_id:=t->>'id';lease:=(t->>'lease_token')::uuid;
  assert public.unsite_claim_collection_task() is null,'one active task per run';
  item:=jsonb_build_object('kind','general','title','Glass orchard','text',passage,'fields','{"real_event":false,"fee":0,"unknown":null}'::jsonb,'context',context,'warnings','[]'::jsonb,'suggested_links','[]'::jsonb,'evidence',jsonb_build_array(jsonb_build_object('segment_id',segment->>'id','source_version_id',vid,'locator',segment->>'locator','quote',passage)));
  assert not public.unsite_collection_result((t->>'id')::uuid,lease,jsonb_build_object('mode','complete','output',jsonb_build_object('candidates',jsonb_build_array(item)))),'model output needs a dispatch reservation';
  dispatch:=public.unsite_collection_dispatch((t->>'id')::uuid,lease,'fixture-model');assert (dispatch->>'allowed')::boolean;
  assert public.unsite_collection_dispatch((t->>'id')::uuid,lease,'fixture-model')->>'reason'='ALREADY_DISPATCHED','one request per lease';
  perform public.unsite_collection_finish((dispatch->>'dispatch_id')::uuid,'succeeded','fixture',10,20);
  denied:=false;begin perform public.unsite_collection_result((t->>'id')::uuid,lease,jsonb_build_object('mode','complete','dispatch_id',dispatch->>'dispatch_id','output',jsonb_build_object('candidates',jsonb_build_array(jsonb_set(item,'{evidence,0,source_version_id}',to_jsonb(gen_random_uuid()))))));exception when raise_exception then denied:=true;end;assert denied,'forged evidence source is rejected atomically';
  assert public.unsite_collection_result((t->>'id')::uuid,lease,jsonb_build_object('mode','complete','dispatch_id',dispatch->>'dispatch_id','output',jsonb_build_object('candidates',jsonb_build_array(item))));
  t:=public.unsite_claim_collection_task();assert t->>'stage'='plan';lease:=(t->>'lease_token')::uuid;
  denied:=false;begin perform public.unsite_collection_result((t->>'id')::uuid,lease,'{"mode":"complete","output":{"batches":[]}}'::jsonb);exception when raise_exception then denied:=true;end;assert denied,'planning cannot omit extracted material';
  assert public.unsite_collection_result((t->>'id')::uuid,lease,jsonb_build_object('mode','complete','output',jsonb_build_object('batches',jsonb_build_array(jsonb_build_object('source_items',jsonb_build_array(extract_id||':0'),'record_ids',jsonb_build_array(recid))))));
  t:=public.unsite_claim_collection_task();assert t->>'stage'='curate';curate_id:=(t->>'id')::uuid;lease:=(t->>'lease_token')::uuid;
  assert public.unsite_collection_context((t->>'id')::uuid,lease)->'run'->'knowledge_snapshot'->'records'->0->>'revision'='1','approved revision is frozen';
  curation:=jsonb_build_object('proposals',jsonb_build_array(item||jsonb_build_object('source_items',jsonb_build_array(extract_id||':0'),'suggested_record_id',recid,'suggested_record_revision',1,'change_reason','Preserve fictional framing and source attribution.')),'unresolved','[]'::jsonb,'summary','The source describes an imagined orchard.');
  dispatch:=public.unsite_collection_dispatch((t->>'id')::uuid,lease,'fixture-model');perform public.unsite_collection_finish((dispatch->>'dispatch_id')::uuid,'succeeded','fixture',10,20);
  assert public.unsite_collection_result((t->>'id')::uuid,lease,jsonb_build_object('mode','complete','dispatch_id',dispatch->>'dispatch_id','output',curation));
  assert not exists(select 1 from public.unsite_candidates where collection_run_id=rid),'unverified proposals are not review candidates';
  t:=public.unsite_claim_collection_task();assert t->>'stage'='verify';lease:=(t->>'lease_token')::uuid;
  dispatch:=public.unsite_collection_dispatch((t->>'id')::uuid,lease,'fixture-model');perform public.unsite_collection_finish((dispatch->>'dispatch_id')::uuid,'succeeded','fixture',10,20);
  verification:='{"verdicts":[{"proposal_index":0,"verdict":"needs_review","issues":["Check that the narrator and author remain distinct."]}]}';
  assert public.unsite_collection_result((t->>'id')::uuid,lease,jsonb_build_object('mode','complete','dispatch_id',dispatch->>'dispatch_id','output',verification));
  assert (select status from public.unsite_collection_runs where id=rid)='completed';
  select id into cid from public.unsite_candidates where collection_run_id=rid and review_ready;
  assert cid is not null,'completed verification releases proposals for owner review';
  reset role;perform set_config('request.jwt.claim.sub',uid::text,true);set local role authenticated;
  denied:=false;begin perform public.unsite_command('review_candidate',jsonb_build_object('space_id',sid,'candidate_id',cid,'revision',1,'decision','accept','kind','general','title','Glass orchard','text',passage,'fields','{}'::jsonb,'context',context));exception when raise_exception then denied:=SQLERRM='Review the verification concerns';end;assert denied,'flagged proposals need acknowledgement';
  perform public.unsite_command('edit_record',jsonb_build_object('space_id',sid,'record_id',recid,'revision',1,'kind','general','title','Owner-edited orchard','text',passage||' This is an owner edit.','fields','{}'::jsonb,'context',context,'active',true));
  denied:=false;begin perform public.unsite_command('review_candidate',jsonb_build_object('space_id',sid,'candidate_id',cid,'revision',1,'decision','accept','verification_reviewed',true,'record_id',recid,'record_revision',1,'kind','general','title','Glass orchard','text',passage,'fields','{}'::jsonb,'context',context));exception when raise_exception then denied:=SQLERRM='Record changed';end;assert denied,'stale update cannot overwrite owner edits';
  s:=public.unsite_command('review_candidate',jsonb_build_object('space_id',sid,'candidate_id',cid,'revision',1,'decision','accept','verification_reviewed',true,'kind','general','title','Glass orchard','text',passage,'fields',item->'fields','context',context));
  assert exists(select 1 from public.unsite_record_evidence where record_id=(s->>'record_id')::uuid and candidate_id=cid),'collection evidence retained in accepted history';
  assert (public.unsite_knowledge_snapshot(sid)->'snapshot')::text not like '%segment_id%','public projection excludes private evidence';
  assert (public.unsite_knowledge_snapshot(sid)->'snapshot')::text not like '%collection_run_id%','public projection excludes private runs';
  -- Second run exercises caps, cancellation, late output fencing, and explicit recovery.
  r:=public.unsite_collection_command('start_collection_run',jsonb_build_object('space_id',sid,'goal','Read again','version_ids',jsonb_build_array(vid),'max_requests',1,'approved',true,'disclosure_version','openai-collection-preparation-2026-09-05','request_id',gen_random_uuid()));rid:=(r->>'id')::uuid;
  reset role;set local role service_role;
  t:=public.unsite_claim_collection_task();lease:=(t->>'lease_token')::uuid;dispatch:=public.unsite_collection_dispatch((t->>'id')::uuid,lease,'fixture-model');
  update public.unsite_collection_tasks set leased_until=now()-interval '1 minute' where id=(t->>'id')::uuid;
  perform public.unsite_claim_collection_task();
  assert (select status from public.unsite_collection_runs where id=rid)='blocked','ambiguous provider work pauses';
  assert (select status from public.unsite_collection_attempts where id=(dispatch->>'dispatch_id')::uuid)='uncertain';
  reset role;perform set_config('request.jwt.claim.sub',uid::text,true);set local role authenticated;
  perform public.unsite_collection_command('resume_collection_run',jsonb_build_object('space_id',sid,'run_id',rid,'max_requests',1,'retry_reviewed',true));
  reset role;set local role service_role;
  t:=public.unsite_claim_collection_task();lease:=(t->>'lease_token')::uuid;
  assert public.unsite_collection_dispatch((t->>'id')::uuid,lease,'fixture-model')->>'reason'='RUN_REQUEST_LIMIT','prior uncertain attempt still consumes budget';
  reset role;perform set_config('request.jwt.claim.sub',uid::text,true);set local role authenticated;
  perform public.unsite_collection_command('cancel_collection_run',jsonb_build_object('space_id',sid,'run_id',rid));
  reset role;set local role service_role;
  assert not public.unsite_collection_result((t->>'id')::uuid,lease,jsonb_build_object('mode','complete','dispatch_id',dispatch->>'dispatch_id','output',jsonb_build_object('candidates',jsonb_build_array(item)))),'cancelled runs discard late output';
  assert public.unsite_collection_dispatch((t->>'id')::uuid,lease,'fixture-model')->>'reason'='STALE_LEASE','cancelled lease cannot dispatch';
  reset role;
end $$;
rollback;
select 'PASS: collection consent, isolation, immutable evidence, coverage, verification, owner revision gates, caps, cancellation and ambiguous recovery' as result;
