-- All users, publications, provider payloads and queues are transactional fixtures.
-- No provider or external request is made, and the transaction is rolled back.
begin;
do $$
declare owner_id uuid:=gen_random_uuid();outsider uuid:=gen_random_uuid();sid uuid;record_id uuid;rid uuid;resource_id uuid:=gen_random_uuid();claim jsonb;snap jsonb;j jsonb;result jsonb;request_id uuid:=gen_random_uuid();denied boolean;v jsonb;chunks jsonb;host_id uuid;
begin
  insert into auth.users(id,aud,role,email,email_confirmed_at) values(owner_id,'authenticated','authenticated',owner_id::text||'@example.invalid',now()),(outsider,'authenticated','authenticated',outsider::text||'@example.invalid',now());
  perform set_config('request.jwt.claim.sub',owner_id::text,true);set local role authenticated;
  sid:=(public.unsite_command('create_space',jsonb_build_object('name','Launch fixture','kind','business','request_id',gen_random_uuid()))->>'id')::uuid;
  perform public.unsite_command('source_intake',jsonb_build_object('space_id',sid,'title','PRIVATE_SOURCE_MARKER','kind','text','text_content','PRIVATE_SOURCE_MARKER is never approved for publication.','request_id',gen_random_uuid()));
  record_id:=(public.unsite_command('create_record',jsonb_build_object('space_id',sid,'title','Delivery entrance','kind','location','text','Use the east entrance for deliveries.','fields','{}'::jsonb,'request_id',gen_random_uuid()))->>'id')::uuid;
  perform public.unsite_presence_command('save_resource',jsonb_build_object('space_id',sid,'id',resource_id,'revision',0,'title','Published guide','description','Public guide','url','https://guide.example.invalid/guide.json','mime_type','application/json','version_label','1','as_of',null,'active',true));
  perform public.unsite_retrieval_case_command('save_retrieval_case',jsonb_build_object('space_id',sid,'question','PRIVATE_QUESTION_MARKER','expectation','no_match','request_id',gen_random_uuid()));
  snap:=public.unsite_knowledge_snapshot(sid);
  rid:=(public.unsite_command('publish_release',jsonb_build_object('space_id',sid,'revision',snap->>'source_revision','reviewed',true,'request_id',gen_random_uuid()))->>'id')::uuid;
  assert (select count(*) from public.unsite_embedding_chunks where space_id=sid)=0,'publication alone does not authorize embeddings';
  denied:=false;begin perform public.unsite_presence_command('save_semantic',jsonb_build_object('space_id',sid,'revision',0,'enabled',true,'daily_query_limit',2));exception when raise_exception then denied:=SQLERRM='Review the semantic search disclosure';end;assert denied,'semantic provider consent required';
  perform public.unsite_presence_command('save_semantic',jsonb_build_object('space_id',sid,'revision',0,'enabled',true,'daily_query_limit',2,'consent','openai-public-embeddings-v1'));
  perform public.unsite_presence_command('index_release',jsonb_build_object('space_id',sid,'release_id',rid,'request_id',request_id,'consent','openai-public-embeddings-v1'));
  perform set_config('request.jwt.claim.sub',outsider::text,true);
  assert (select count(*) from public.unsite_embedding_chunks where space_id=sid)=0,'embedding tenant RLS';
  denied:=false;begin perform public.unsite_presence_command('save_semantic',jsonb_build_object('space_id',sid,'revision',1,'enabled',false,'daily_query_limit',2));exception when insufficient_privilege then denied:=true;end;assert denied,'outsider cannot disable indexing';
  reset role;set local role service_role;
  assert not public.unsite_semantic_available(sid,rid),'incomplete index unavailable';
  j:=public.unsite_claim_embeddings();assert j->>'release_id'=rid::text,'only current authorized release is queued';
  assert position('PRIVATE_SOURCE_MARKER' in j::text)=0 and position('PRIVATE_QUESTION_MARKER' in j::text)=0,'private source and questions excluded';
  assert public.unsite_embedding_result(rid,gen_random_uuid(),'{"error":"wrong lease"}')->>'saved'='false','embedding lease fenced';
  select jsonb_agg(case when n=1 then 1 else 0 end order by n) into v from generate_series(1,512) n;
  select jsonb_agg(jsonb_build_object('id',c->>'id','embedding',v)) into chunks from jsonb_array_elements(j->'chunks') c;
  assert public.unsite_embedding_result(rid,(j->>'lease')::uuid,jsonb_build_object('chunks',chunks,'tokens',20))->>'saved'='true','embedding checkpoint saved';
  assert public.unsite_semantic_available(sid,rid),'complete authorized index available';
  result:=public.unsite_hybrid_records(sid,rid,'unrelatedword',v::text::extensions.vector,8);
  assert result->'records'->0->>'id'=record_id::text,'semantic-only match survives lexical miss';
  assert jsonb_array_length(public.unsite_hybrid_records(sid,rid,'unrelatedword',v::text::extensions.vector,8,'','policy')->'records')=0,'hybrid filters before ranking';
  assert public.unsite_semantic_query_budget(sid,rid) and public.unsite_semantic_query_budget(sid,rid) and not public.unsite_semantic_query_budget(sid,rid),'daily budget is atomically bounded';
  update public.unsite_embedding_chunks set status='running',lease_token=gen_random_uuid(),leased_until=now()-interval '1 second',embedding=null where release_id=rid;
  assert public.unsite_claim_embeddings() is null,'uncertain expired embedding calls are not replayed';
  assert (select bool_and(status='blocked' and error_code='provider_uncertain') from public.unsite_embedding_chunks where release_id=rid),'expired provider attempts require review';
  update public.unsite_embedding_chunks set status='ready',embedding=v::text::extensions.vector,error_code=null,error_message=null where release_id=rid;

  reset role;set local role authenticated;perform set_config('request.jwt.claim.sub',owner_id::text,true);
  perform public.unsite_presence_command('index_release',jsonb_build_object('space_id',sid,'release_id',rid,'request_id',request_id,'consent','openai-public-embeddings-v1'));
  assert (select count(*) from public.unsite_embedding_chunks where release_id=rid and status='queued')=0,'idempotent authorization cannot replay ready chunks';
  claim:=public.unsite_presence_command('claim_domain',jsonb_build_object('space_id',sid,'domain','knowledge.example.invalid','request_id',gen_random_uuid()));
  denied:=false;begin perform public.unsite_presence_command('register_host',jsonb_build_object('space_id',sid,'claim_id',claim->>'id','revision',0));exception when raise_exception then denied:=SQLERRM='Verify this exact hostname before connecting it';end;assert denied,'unverified host cannot become canonical';
  reset role;set local role service_role;
  update public.unsite_domain_claims set status='verified',expires_at=now()+interval '7 days' where id=(claim->>'id')::uuid;
  reset role;set local role authenticated;
  perform public.unsite_presence_command('register_host',jsonb_build_object('space_id',sid,'claim_id',claim->>'id','revision',0));
  reset role;set local role service_role;
  assert public.unsite_public_host('knowledge.example.invalid')->>'routable'='false','DNS proof alone does not claim working hosting';
  j:=public.unsite_claim_launch_job();assert j->>'kind'='resource','resource availability queued only after publication';
  assert j->'payload'->>'url'='https://guide.example.invalid/guide.json','only approved external URL is checked';
  assert public.unsite_launch_result((j->>'id')::uuid,gen_random_uuid(),'{"ok":true}')->>'saved'='false','resource check lease fenced';
  perform public.unsite_launch_result((j->>'id')::uuid,(j->>'lease')::uuid,'{"ok":true,"http_status":200,"content_type":"application/json"}');
  j:=public.unsite_claim_launch_job();assert j->>'kind'='host','host proof uses a dedicated check';
  host_id:=(j->'payload'->>'host_id')::uuid;
  perform public.unsite_launch_result((j->>'id')::uuid,(j->>'lease')::uuid,'{"ok":true,"method":"https_workspace_proof"}');
  assert public.unsite_public_host('knowledge.example.invalid')->>'routable'='true','HTTPS proof activates verified mapping';
  assert public.unsite_public_metadata(sid)->>'canonical_origin'='https://knowledge.example.invalid','canonical API metadata follows mapping';
  update public.unsite_domain_claims set expires_at=now()-interval '1 second' where id=(claim->>'id')::uuid;
  assert public.unsite_public_host('knowledge.example.invalid') is null and public.unsite_public_metadata(sid)->>'canonical_origin' is null,'expired ownership stops routing immediately';
  update public.unsite_domain_claims set expires_at=now()+interval '7 days' where id=(claim->>'id')::uuid;
  reset role;set local role authenticated;
  perform public.unsite_presence_command('save_discovery',jsonb_build_object('space_id',sid,'revision',0,'google_token','verified_google_token','bing_token','','indexnow_enabled',true,'consent','indexnow-public-urls-v1'));
  reset role;set local role service_role;
  j:=public.unsite_claim_launch_job();assert j->>'kind'='indexnow','owner consent queues public search submission';
  assert position('PRIVATE_QUESTION_MARKER' in j::text)=0 and position('PRIVATE_SOURCE_MARKER' in j::text)=0 and position('guide.example.invalid' in j::text)=0,'no private questions or third-party resource URLs in discovery payload';
  assert jsonb_array_length(j->'payload'->'urls')=2,'only canonical root and approved record submitted';
  perform public.unsite_launch_result((j->>'id')::uuid,(j->>'lease')::uuid,'{"ok":true,"http_status":202,"state":"validation_pending","indexed":null,"url_count":2}');
  reset role;set local role authenticated;
  perform public.unsite_command('unpublish',jsonb_build_object('space_id',sid,'reviewed',true));
  reset role;set local role service_role;
  assert public.unsite_public_metadata(sid) is null and not public.unsite_semantic_available(sid,rid),'unpublish removes public and semantic reads';
  assert public.unsite_public_host('knowledge.example.invalid')->>'published'='false','routing binding records unpublish';
  assert public.unsite_public_host('knowledge.example.invalid')->>'indexnow_key' is not null,'verification file remains available for removal notifications';
  j:=public.unsite_claim_launch_job();assert j->>'kind'='indexnow' and jsonb_array_length(j->'payload'->'urls')=2,'unpublish queues deleted public URLs';
  reset role;
end $$;
rollback;
select 'PASS: semantic authorization, tenant isolation, public-only input, vector retrieval, daily budget, hostname proof/expiry, resource leases, IndexNow consent, and unpublish removals' as result;
