-- Authorization, immutable publication, monitoring and index regression tests.
-- Every fixture and queued task is rolled back; no external request is sent.
begin;
do $$
declare owner_id uuid:=gen_random_uuid();outsider uuid:=gen_random_uuid();sid uuid;rid uuid:=gen_random_uuid();resource_id uuid:=gen_random_uuid();
  p jsonb;claim jsonb;job jsonb;snap jsonb;release jsonb;version_input jsonb;result jsonb;denied boolean;first_challenge text;old_count integer;
begin
  insert into auth.users(id,aud,role,email,email_confirmed_at) values
    (owner_id,'authenticated','authenticated',owner_id::text||'@example.invalid',now()),
    (outsider,'authenticated','authenticated',outsider::text||'@example.invalid',now());
  perform set_config('request.jwt.claim.sub',owner_id::text,true);
  set local role authenticated;
  sid:=(public.unsite_command('create_space',jsonb_build_object('name','GEO fixture','kind','business','request_id',gen_random_uuid()))->>'id')::uuid;
  p:=jsonb_build_object('space_id',sid,'revision',0,'entity_type','Organization','official_url','https://example.invalid/','aliases','["Fixture alias"]'::jsonb,'profile_urls','["https://profiles.example.invalid/fixture"]'::jsonb);
  perform public.unsite_presence_command('save_publisher',p);
  denied:=false;begin perform public.unsite_presence_command('save_publisher',p);exception when raise_exception then denied:=SQLERRM='Record changed';end;assert denied,'stale identity revision rejected';
  claim:=public.unsite_presence_command('claim_domain',jsonb_build_object('space_id',sid,'domain','example.invalid','request_id',gen_random_uuid()));
  first_challenge:=claim->>'challenge';
  assert length(first_challenge)=64 and claim->>'status'='pending','proof begins unverified with unpredictable token';
  assert not(claim ? 'lease_token'),'private lease never disclosed';
  perform public.unsite_presence_command('save_resource',jsonb_build_object('space_id',sid,'id',resource_id,'revision',0,'title','Public specification','description','Approved external documentation','url','https://example.invalid/spec/v1.json','mime_type','application/json','version_label','1','as_of','2026-09-01','active',true));
  perform public.unsite_command('create_record',jsonb_build_object('space_id',sid,'title','Refund policies','kind','policy','text','Reimbursements are available within thirty days.','fields','{}'::jsonb,'request_id',gen_random_uuid()));
  snap:=public.unsite_knowledge_snapshot(sid);
  assert snap->'snapshot'->'publisher'->>'official_url'='https://example.invalid/','review includes publisher identity';
  assert jsonb_array_length(snap->'snapshot'->'resources')=1,'review includes approved resources';
  perform public.unsite_retrieval_case_command('save_retrieval_case',jsonb_build_object('space_id',sid,'question','Refund policies','expectation','find','expected_record_id',snap->'snapshot'->'records'->0->>'id','request_id',gen_random_uuid()));
  release:=public.unsite_command('publish_release',jsonb_build_object('space_id',sid,'revision',snap->>'source_revision','reviewed',true,'request_id',gen_random_uuid()));
  perform public.unsite_presence_command('save_publisher',p||'{"revision":1,"aliases":["Private draft alias"]}');
  perform set_config('request.jwt.claim.sub',outsider::text,true);
  denied:=false;begin perform public.unsite_presence_state(sid);exception when insufficient_privilege then denied:=true;end;assert denied,'presence state tenant isolation';
  denied:=false;begin perform public.unsite_presence_command('check_domain',jsonb_build_object('space_id',sid,'claim_id',claim->>'id'));exception when insufficient_privilege then denied:=true;end;assert denied,'domain writes tenant isolation';
  assert (select count(*) from public.unsite_public_resources where space_id=sid)=0,'resource table RLS';
  denied:=false;begin perform public.unsite_public_metadata(sid);exception when insufficient_privilege then denied:=true;end;assert denied,'customer cannot call privileged projection RPC';
  reset role;
  set local role service_role;
  result:=public.unsite_public_metadata(sid);
  assert result->'data'->'publisher'->'aliases'='["Fixture alias"]'::jsonb,'public metadata frozen at approved release';
  assert result->'data'->'records'='[]'::jsonb and (result->>'record_count')::integer=1,'metadata does not load complete release records';
  assert result->'authority'->>'status'='unverified','pending domain never shown as verified';
  result:=public.unsite_public_records(sid,(release->>'id')::uuid,null,'policy OR reimbursement');
  assert (result->>'total')::integer=1,'English stemming retrieves plural terms';
  rid:=(result->'records'->0->>'id')::uuid;
  assert jsonb_array_length(public.unsite_public_records(sid,(release->>'id')::uuid,rid)->'records')=1,'indexed record fetch';
  assert public.unsite_public_records(sid,gen_random_uuid())->>'changed'='true','release fence rejects mixed snapshots';
  assert public.unsite_public_read_budget(sid),'first request within read quota';
  update public.unsite_public_read_windows set count=3000 where space_id=sid;
  assert not public.unsite_public_read_budget(sid),'public read quota bounds requests';
  job:=public.unsite_claim_maintenance();assert job->>'kind'='delivery','publishing automatically queues a delivery check';
  assert not(job ? 'cases') and not(job ? 'index_results'),'private retrieval questions never enter external delivery tasks';
  assert (select index_results->0->>'passed'='true' from public.unsite_delivery_checks where id=(job->>'id')::uuid),'saved questions are checked inside the release index';
  perform public.unsite_maintenance_result('delivery',(job->>'id')::uuid,(job->>'lease')::uuid,jsonb_build_object('mode','direct_http_mcp','release_id',release->>'id','checks','[]'::jsonb,'passed',true));
  assert (select status='completed' from public.unsite_delivery_checks where id=(job->>'id')::uuid),'delivery results stored under a fenced worker lease';
  job:=public.unsite_claim_maintenance();assert job->>'kind'='domain','due domain is claimed';
  assert public.unsite_maintenance_result('domain',(job->>'id')::uuid,gen_random_uuid(),'{"verified":true}')->>'saved'='false','wrong lease cannot verify identity';
  perform public.unsite_maintenance_result('domain',(job->>'id')::uuid,(job->>'lease')::uuid,'{"verified":true}');
  assert public.unsite_public_metadata(sid)->'authority'->>'status'='verified','successful proof becomes public';
  update public.unsite_domain_claims set expires_at=now()-interval '1 minute' where space_id=sid;
  assert public.unsite_public_metadata(sid)->'authority'->>'status'='unverified','expiry checked at read time';
  reset role;
  set local role authenticated;
  perform set_config('request.jwt.claim.sub',owner_id::text,true);
  perform public.unsite_presence_command('revoke_domain',jsonb_build_object('space_id',sid,'claim_id',claim->>'id'));
  claim:=public.unsite_presence_command('claim_domain',jsonb_build_object('space_id',sid,'domain','example.invalid','request_id',gen_random_uuid()));
  assert claim->>'challenge'<>first_challenge and claim->>'status'='pending','reclaim rotates proof and clears verification';
  perform public.unsite_presence_command('revoke_domain',jsonb_build_object('space_id',sid,'claim_id',claim->>'id'));
  version_input:=public.unsite_command('source_intake',jsonb_build_object('space_id',sid,'title','Monitored source','kind','url','origin_url','https://example.invalid/policy','request_id',gen_random_uuid()));
  perform public.unsite_presence_command('save_monitor',jsonb_build_object('space_id',sid,'source_id',version_input->>'source_id','cadence','daily'));
  reset role;
  set local role service_role;
  update public.unsite_source_versions set extracted_text='The first version.',content_hash=repeat('a',64) where id=(version_input->>'id')::uuid;
  select count(*) into old_count from public.unsite_source_versions where space_id=sid;
  job:=public.unsite_claim_maintenance();assert job->>'kind'='source','source monitor has independent queue';
  result:=public.unsite_maintenance_result('source',(job->>'id')::uuid,(job->>'lease')::uuid,'{"text":"  The first   version. \n"}');
  assert result->>'changed'='false' and (select count(*) from public.unsite_source_versions where space_id=sid)=old_count,'whitespace-only changes do not create versions';
  update public.unsite_source_monitors set next_check_at=now() where space_id=sid;
  job:=public.unsite_claim_maintenance();
  result:=public.unsite_maintenance_result('source',(job->>'id')::uuid,(job->>'lease')::uuid,'{"text":"The second version changes the policy."}');
  assert result->>'changed'='true' and (select count(*) from public.unsite_source_versions where space_id=sid)=old_count+1,'changed text creates exactly one private version';
  assert (select error_code='AI_APPROVAL_REQUIRED' and status='blocked' from public.unsite_jobs where source_version_id=(result->>'version_id')::uuid),'monitoring does not authorize AI preparation';
  assert (select count(*) from public.unsite_source_changes where space_id=sid)=1,'source change recorded';
  assert public.unsite_maintenance_result('source',(job->>'id')::uuid,(job->>'lease')::uuid,'{"text":"The second version changes the policy."}')->>'saved'='false','completed lease cannot duplicate a version';
  reset role;
  set local role authenticated;
  perform public.unsite_command('unpublish',jsonb_build_object('space_id',sid,'reviewed',true));
  reset role;
  set local role service_role;
  assert public.unsite_public_metadata(sid) is null and public.unsite_public_records(sid,(release->>'id')::uuid) is null,'unpublish blocks metadata and historical record reads';
  assert not exists(select 1 from jsonb_array_elements(public.unsite_public_directory()->'items') x where x->>'id'=sid::text),'directory excludes unpublished content';
  reset role;
end $$;
rollback;
select 'PASS: identity, ownership leases, tenant isolation, approved release index, stemming, quotas, source change detection, AI approval, and unpublish' as result;
