-- Run against a development project as postgres. Every fixture is rolled back.
begin;
do $$
declare
  a uuid:=gen_random_uuid(); b uuid:=gen_random_uuid(); request_id uuid:=gen_random_uuid(); sid uuid;
  s jsonb; version jsonb; draft jsonb; release jsonb; later jsonb; job jsonb; candidate uuid; dispatch jsonb; before_revision integer; denied boolean;
begin
  insert into auth.users(id,aud,role,email) values(a,'authenticated','authenticated',a::text||'@example.invalid'),(b,'authenticated','authenticated',b::text||'@example.invalid');
  perform set_config('request.jwt.claim.sub',a::text,true);
  set local role authenticated;
  s:=public.unsite_command('create_space',jsonb_build_object('name','Isolation fixture','kind','business','request_id',request_id)); sid:=(s->>'id')::uuid;
  assert (public.unsite_command('create_space',jsonb_build_object('name','Ignored retry','kind','person','request_id',request_id))->>'id')::uuid=sid,'create idempotency';
  assert (select count(*) from public.unsite_spaces where id=sid)=1,'owner read';
  denied:=false;begin update public.unsite_spaces set name='bypass' where id=sid;exception when insufficient_privilege then denied:=true;end;assert denied,'direct writes must be denied';
  version:=public.unsite_command('source_intake',jsonb_build_object('space_id',sid,'title','Private original','kind','text','text_content','CONFIDENTIAL: Internal rates are never a public source.','request_id',request_id));
  assert public.unsite_command('source_intake',jsonb_build_object('space_id',sid,'title','Private original','kind','text','text_content','CONFIDENTIAL: Internal rates are never a public source.','request_id',request_id))->>'id'=version->>'id','source idempotency';
  draft:=public.unsite_command('create_record',jsonb_build_object('space_id',sid,'title','Offering','kind','offering','text','A deliberately approved public description.','fields','{"currency":"USD"}'::jsonb,'request_id',request_id));
  assert public.unsite_command('create_record',jsonb_build_object('space_id',sid,'title','Offering','kind','offering','text','A deliberately approved public description.','fields','{}'::jsonb,'request_id',request_id))->>'id'=draft->>'id','record idempotency';
  select content_revision into before_revision from public.unsite_spaces where id=sid;
  release:=public.unsite_command('publish_release',jsonb_build_object('space_id',sid,'revision',before_revision,'reviewed',true,'request_id',request_id,'summary','First release'));
  assert public.unsite_command('publish_release',jsonb_build_object('space_id',sid,'revision',before_revision,'reviewed',true,'request_id',request_id))->>'id'=release->>'id','publication idempotency';
  assert not (select data::text like '%CONFIDENTIAL%' from public.unsite_releases where id=(release->>'id')::uuid),'private original must not leak';
  denied:=false;begin perform public.unsite_command('update_space',jsonb_build_object('space_id',sid,'name','stale','kind','business','revision',1));exception when raise_exception then denied:=SQLERRM='Record changed';end;assert denied,'stale revision must fail';
  denied:=false;begin perform public.unsite_command('update_space',jsonb_build_object('space_id',sid,'name','no revision','kind','business'));exception when raise_exception then denied:=SQLERRM='Record changed';end;assert denied,'missing revision must fail';
  draft:=public.unsite_command('edit_record',jsonb_build_object('space_id',sid,'record_id',draft->>'id','revision',1,'title','Offering','kind','offering','text','Updated public description.','fields','{}'::jsonb,'active',true));
  select content_revision into before_revision from public.unsite_spaces where id=sid;
  later:=public.unsite_command('publish_release',jsonb_build_object('space_id',sid,'revision',before_revision,'reviewed',true,'request_id',gen_random_uuid()));
  assert (select data->'records'->0->>'text' from public.unsite_releases where id=(release->>'id')::uuid)='A deliberately approved public description.','release immutability';
  perform public.unsite_command('rollback_release',jsonb_build_object('space_id',sid,'release_id',release->>'id','reviewed',true));
  assert (select active_release_id from public.unsite_spaces where id=sid)=(release->>'id')::uuid,'rollback pointer';
  perform set_config('request.jwt.claim.sub',b::text,true);
  assert (select count(*) from public.unsite_spaces where id=sid)=0,'cross-account space isolation';
  assert (select count(*) from public.unsite_source_versions where space_id=sid)=0,'cross-account source isolation';
  assert (select count(*) from public.unsite_releases where space_id=sid)=0,'cross-account history isolation';
  denied:=false;begin perform public.unsite_command('unpublish',jsonb_build_object('space_id',sid,'reviewed',true));exception when insufficient_privilege then denied:=true;end;assert denied,'cross-account mutation denied';
  perform set_config('request.jwt.claim.sub',a::text,true);
  perform public.unsite_ai_command('prepare_source',jsonb_build_object('space_id',sid,'version_id',version->>'id','approved',true,'disclosure_version','openai-source-preparation-2026-09-05','request_id',gen_random_uuid()));
  reset role;
  set local role service_role;
  job:=public.unsite_claim_job();
  assert (job->>'source_version_id')::uuid=(version->>'id')::uuid,'claim source';
  assert public.unsite_claim_job() is null,'live lease must not be claimed twice';
  assert public.unsite_job_result((job->>'id')::uuid,gen_random_uuid(),'{"mode":"parsed","text":"fake","hash":"fake","chunks":1}'::jsonb)=false,'wrong lease rejected';
  assert public.unsite_job_result((job->>'id')::uuid,(job->>'lease_token')::uuid,'{"mode":"parsed","text":"Supported source passage.","hash":"fixture","chunks":1}'::jsonb),'parser checkpoint';
  dispatch:=public.unsite_ai_dispatch((job->>'id')::uuid,(job->>'lease_token')::uuid,'test-model');
  assert (dispatch->>'allowed')::boolean,'authorized fixture dispatch';
  perform public.unsite_ai_finish((dispatch->>'dispatch_id')::uuid,'succeeded','test-response',10,10);
  assert public.unsite_job_result((job->>'id')::uuid,(job->>'lease_token')::uuid,jsonb_build_object('mode','chunk','cursor',0,'dispatch_id',dispatch->>'dispatch_id','candidates',jsonb_build_array(jsonb_build_object('kind','offering','title','Offering','text','Supported source passage.','fields','{}'::jsonb,'evidence',jsonb_build_array(jsonb_build_object('quote','Supported source passage.','locator','Passage 1','source_version_id',version->>'id')),'warnings','[]'::jsonb)))),'candidate checkpoint';
  assert (select status from public.unsite_jobs where id=(job->>'id')::uuid)='completed','durable completion';
  assert public.unsite_job_result((job->>'id')::uuid,(job->>'lease_token')::uuid,'{"mode":"chunk","cursor":0,"candidates":[]}'::jsonb)=false,'late result rejected';
  select id into candidate from public.unsite_candidates where job_id=(job->>'id')::uuid;
  assert (select jsonb_array_length(warnings) from public.unsite_candidates where id=candidate)=1,'potential duplicate flagged';
  reset role;
  perform set_config('request.jwt.claim.sub',a::text,true);
  set local role authenticated;
  perform public.unsite_command('review_candidate',jsonb_build_object('space_id',sid,'candidate_id',candidate,'revision',1,'decision','accept','record_id',draft->>'id','record_revision',2,'title','Offering','kind','offering','text','Supported source passage.','fields','{}'::jsonb));
  assert (select count(*) from public.unsite_records where space_id=sid)=1,'reviewed update preserves stable record';
  assert (select revision from public.unsite_records where id=(draft->>'id')::uuid)=3,'reviewed update revision';
  perform public.unsite_command('unpublish',jsonb_build_object('space_id',sid,'reviewed',true));
  assert (select active_release_id from public.unsite_spaces where id=sid) is null,'unpublish pointer';
  reset role;
end $$;
rollback;
select 'PASS: isolation, optimistic concurrency, idempotency, private-source exclusion, immutable releases, rollback, leases and reviewed updates' as result;
