"use client";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {ArrowUpRight,BookOpen,Check,FlaskConical,Link2,Plus,Search,Trash2} from "@/components/unsite/icons";
import {Input} from "@/components/ui/input";
import type {RuntimeStatus,SpaceState} from "@/lib/production/types";
import {contextOf,entryType,relationLabels,statusLabels} from "@/lib/production/knowledge";
import {inspectKnowledge,searchKnowledge,type RetrievalCase,type SearchHit} from "@/lib/production/retrieval";
import {recordMarkdown,type PublishedRecord,type Snapshot} from "@/lib/production/release";
import {Action,useApi,Busy,Choice,Empty,ErrorNotice,External,Field,Modal,Pill,saveFile,type Command} from "./shared";
type KnowledgeData={snapshot:Snapshot;source_revision:number;cases:RetrievalCase[]};
type Report={mode:string;source_revision:number;release_id?:string;inspection:ReturnType<typeof inspectKnowledge>;cases:(RetrievalCase&{passed:boolean;returned_titles:string[];error?:string})[];transport?:{entry_point:string;manifest_status:number;bundle_status:number;checked_at:string}|null};
import {ReadingContext} from "./context-editor";
export function AgentLab({state,status,command,canEdit,sample=false}:{state:SpaceState;status:RuntimeStatus|null;command:Command;canEdit:boolean;sample?:boolean}){
  const api=useApi();
  const [data,setData]=useState<KnowledgeData|null>(null),[mode,setMode]=useState("draft"),[query,setQuery]=useState(""),[hits,setHits]=useState<SearchHit[]|null>(null),[selected,setSelected]=useState<PublishedRecord|null>(null),[report,setReport]=useState<Report|null>(null),[error,setError]=useState(""),[busy,setBusy]=useState(""),[adding,setAdding]=useState(false),[question,setQuestion]=useState(""),[expected,setExpected]=useState("no_match"),[liveSnapshot,setLiveSnapshot]=useState<Snapshot|null>(null);
  const request=useRef(crypto.randomUUID()),sequence=useRef(0),base=status?.publicBase?status.publicBase+"/"+state.space.id:null;
  const snapshot=mode==="published"?liveSnapshot:data?.snapshot;
  async function load(){setData(await api<KnowledgeData>("/api/app/knowledge?space="+state.space.id));}
  useEffect(()=>{let active=true;api<KnowledgeData>("/api/app/knowledge?space="+state.space.id).then(d=>active&&setData(d)).catch(e=>active&&setError(e.message));return()=>{active=false;};},[api,state.space.id,state.space.content_revision]);
  useEffect(()=>{const seq=++sequence.current;setHits(null);setReport(null);setLiveSnapshot(null);setSelected(null);if(mode==="published"&&state.space.active_release_id)api<{release:{data:Snapshot}}>("/api/app/release?id="+state.space.active_release_id).then(d=>seq===sequence.current&&setLiveSnapshot(d.release.data)).catch(e=>seq===sequence.current&&setError(e.message));},[api,mode,state.space.active_release_id]);
  useEffect(()=>{if(!state.space.active_release_id)setMode("draft");},[api,state.space.active_release_id]);
  useEffect(()=>{if(mode==="draft"){setHits(null);setSelected(null);}},[data?.source_revision,mode]);
  async function search(e:FormEvent){e.preventDefault();const seq=sequence.current;setBusy("search");setError("");try{
    if(mode==="published"&&!sample){if(!base)throw new Error("The public connection is unavailable.");const response=await fetch(base+"/search?q="+encodeURIComponent(query)+"&limit=8&release="+state.space.active_release_id);if(!response.ok)throw new Error("The publication may have changed or could not be reached. Refresh and retry.");const found=await response.json() as {results:SearchHit[]};if(seq===sequence.current)setHits(found.results);}
    else if(snapshot)setHits(searchKnowledge(snapshot,query,{limit:8}).results);
  }catch(e){setError((e as Error).message);}finally{setBusy("");}}
  async function check(){const seq=sequence.current;setBusy("check");setError("");try{const next=await api<Report>("/api/app/agent-check?space="+state.space.id+"&mode="+mode);if(seq===sequence.current)setReport(next);}catch(e){setError((e as Error).message);}finally{setBusy("");}}
  async function addCase(e:FormEvent){e.preventDefault();setBusy("save");setError("");try{await command("save_retrieval_case",{question,expectation:expected==="no_match"?"no_match":"find",expected_record_id:expected==="no_match"?null:expected,request_id:request.current});await load();setAdding(false);setReport(null);}catch(e){setError((e as Error).message);}finally{setBusy("");}}
  async function removeCase(id:string){setBusy(id);setError("");try{await command("delete_retrieval_case",{case_id:id});await load();setReport(null);}catch(e){setError((e as Error).message);}finally{setBusy("");}}
  return <>
    <div className="us-section-heading"><div><span className="us-eyebrow">Make knowledge usable</span><h1>Agent access</h1><p>Inspect retrieval, follow relationships, and check important questions.</p></div><Choice label="Knowledge version" value={mode} onChange={v=>!busy&&setMode(v)} items={[{value:"draft",label:"Approved draft"},...(state.space.active_release_id?[{value:"published",label:"Published knowledge"}]:[])]}/></div>
    <ErrorNotice message={error}/>
    {mode==="draft"&&<div className="us-notice">Draft inspection stays private. Publish a release to make this knowledge reachable by external agents.</div>}
    {!snapshot?<Busy label="Loading knowledge…"/>:!snapshot.records.length?<Empty icon={<BookOpen size={30}/>} title="Approve some knowledge first" description="Review source suggestions or add an entry. Approved knowledge will appear here before publication."/>:<>
      <section className="us-card us-retrieval-search"><form onSubmit={search}><Field label="What should an agent be able to find?">{id=><Input id={id} required minLength={2} maxLength={300} value={query} onChange={e=>setQuery(e.target.value)} placeholder="What does this collection say about memory?"/>}</Field><Action type="submit" disabled={!!busy}>{busy==="search"?<Busy label="Searching…"/>:<><Search size={17}/>Retrieve knowledge</>}</Action></form><p className="us-small us-muted">Results use words, aliases, and topics. Inspect the full record before drawing conclusions from an excerpt.</p></section>
      {hits!==null&&<section className="us-retrieval-results"><div className="us-between"><h3>{hits.length?"Retrieved records":"No matching records"}</h3><Pill>{sample?"Sample knowledge":mode==="published"?"From the public endpoint":"Private draft"}</Pill></div>{!hits.length?<p className="us-muted">No match was found for these terms. The information may be missing or described differently.</p>:hits.map(hit=><button className="us-card us-retrieval-hit" key={hit.id} onClick={()=>setSelected(snapshot.records.find(r=>r.id===hit.id)||null)}><div className="us-between"><h3>{hit.title}</h3><Pill>{entryType(hit)}</Pill></div><ReadingContext value={hit.context}/><p>{hit.excerpt}</p><span className="us-small us-muted">Matched: {hit.matched_terms.join(", ")}</span><span className="us-small us-green">Read complete context <ArrowUpRight size={14}/></span></button>)}</section>}
      <div className="us-agent-grid">
        <section className="us-card"><div className="us-between"><h3>Connected knowledge</h3><Pill>{snapshot.records.length} entries</Pill></div><div className="us-knowledge-directory">{snapshot.records.map(record=><button key={record.id} onClick={()=>setSelected(record)}><span><strong>{record.title}</strong><small>{record.context?.summary||record.text.slice(0,140)}</small></span><span>{record.links?.length||0}<Link2 size={14}/></span></button>)}</div></section>
        <section className="us-card"><div className="us-between"><h3>Retrieval checks</h3><FlaskConical size={20}/></div><p>Save questions and the entries you expect them to retrieve. Rerun them after an update.</p><div className="us-inline-actions"><Action secondary disabled={!!busy} onClick={check}>{busy==="check"?<Busy label="Checking…"/>:"Run checks"}</Action>{canEdit&&<button onClick={()=>{setAdding(true);setQuestion(query);setExpected("no_match");request.current=crypto.randomUUID();}} disabled={(data?.cases.length||0)>=20}><Plus size={15}/>Add a question</button>}</div>{data?.cases.map(c=><div className="us-case-row" key={c.id}><span><strong>{c.question}</strong><small>{c.expectation==="no_match"?"Expect no retrieval match":data.snapshot.records.find(r=>r.id===c.expected_record_id)?.title||"Expected entry is not included"}</small></span>{canEdit&&<button className="us-icon-button" aria-label={"Remove question: "+c.question} onClick={()=>void removeCase(c.id)} disabled={!!busy}><Trash2 size={15}/></button>}</div>)}{!data?.cases.length&&<p className="us-small us-muted">No saved questions yet. General checks can still inspect the publication's structure.</p>}<p className="us-small us-muted">These checks assess retrieval and structure. They do not certify factual accuracy or a model’s understanding.</p></section>
      </div>
      {report&&<section className="us-card us-check-report"><div className="us-between"><div><h3>Check results</h3><p className="us-small us-muted">{sample?"Checked sample knowledge locally.":report.mode==="published"?"Public endpoints were contacted directly.":"Checked approved draft revision "+report.source_revision+"."}{report.mode==="draft"&&report.source_revision!==state.space.content_revision?" Knowledge changed. Run the check again.":""}</p></div><button className="us-link" onClick={()=>saveFile("unsite-retrieval-checks.json",report)}>Export report</button></div>{report.transport&&<p className="us-success"><Check size={15}/>Manifest and knowledge retrieved successfully from the public address.</p>}{report.inspection.checks.map(c=><div className="us-check-row" key={c.id}><span><strong>{c.label}</strong><small>{c.detail}{c.record_ids.length>0?" "+c.record_ids.length+" item(s) to review.":""}</small></span><Pill tone={c.status==="pass"?"green":"amber"}>{c.status==="pass"?"Passed":"Review"}</Pill></div>)}{report.cases.map(c=><div className="us-check-row" key={c.id}><span><strong>{c.question}</strong><small>{c.error||c.returned_titles.join(" · ")||"No results returned"}</small></span><Pill tone={c.passed?"green":"amber"}>{c.passed?"Matched expectation":"Check result"}</Pill></div>)}</section>}
      {base&&state.space.active_release_id&&<section className="us-card us-agent-connections"><h3>Connect an agent</h3><p>Give a browsing agent the discovery index, or use the MCP address in a compatible server client.</p><Field label="MCP server address">{id=><Input id={id} readOnly value={base+"/mcp"}/>}</Field><div className="us-inline-actions"><External href={base+"/llms.txt"}>Discovery index</External><External href={base+"/catalog.md"}>Knowledge directory</External><External href={base+"/openapi.json"}>API definition</External></div></section>}
    </>}
    {selected&&snapshot&&<Modal open onClose={()=>setSelected(null)} title={selected.title} description="Complete approved context and its relationships." wide><div className="us-between"><Pill>{entryType(selected)}</Pill><span className="us-small us-muted">Record revision {selected.revision}</span></div><ReadingContext value={selected.context}/>{contextOf(selected.context).summary&&<p>{selected.context!.summary}</p>}<div className="us-record-body">{selected.text}</div><dl className="us-record-facts">{Object.entries(selected.fields).map(([key,value])=><div key={key}><dt>{key}</dt><dd>{value===null?"Unknown":String(value)}</dd></div>)}</dl><p className="us-small us-muted">Knowledge status: {statusLabels[contextOf(selected.context).status]} · As of: {contextOf(selected.context).as_of||"not specified"}</p>{(selected.links||[]).map(link=>{const target=snapshot.records.find(r=>r.id===link.target_id);return target?<button key={link.relation+link.target_id} className="us-record-relationship" onClick={()=>setSelected(target)}><span>{relationLabels[link.relation]}</span><strong>{target.title}</strong><ArrowUpRight size={16}/></button>:null;})}<div className="us-modal-actions"><button className="us-link" onClick={()=>saveFile("unsite-record.md",recordMarkdown(selected,mode==="published"?base||undefined:undefined,mode==="published"?state.space.active_release_id||undefined:undefined),"text/markdown")}>Download Markdown</button>{selected.source_url&&<External href={selected.source_url}>Public source</External>}</div></Modal>}
    {adding&&data&&<Modal open onClose={()=>!busy&&setAdding(false)} title="Add a retrieval question" description="An expected entry must appear among the first five results. Choose no match to test a query that should return nothing."><form onSubmit={addCase}><Field label="Question or search query">{id=><Input id={id} required minLength={2} maxLength={300} value={question} onChange={e=>setQuestion(e.target.value)}/>}</Field><Field label="Expected result">{()=> <Choice label="Expected retrieval result" value={expected} onChange={setExpected} items={[{value:"no_match",label:"No retrieval match"},...data.snapshot.records.map(r=>({value:r.id,label:r.title}))]}/>}</Field><ErrorNotice message={error}/><div className="us-modal-actions"><Action type="submit" disabled={!!busy}>{busy==="save"?<Busy label="Saving…"/>:"Save question"}</Action></div></form></Modal>}
  </>;
}
