"use client";
import {useState,type FormEvent} from "react";
import {ArrowRight,LockKeyhole,Check,Braces,FileText} from "lucide-react";
import {Input} from "@/components/ui/input";
import {Action,api,Busy,ErrorNotice,Field} from "./shared";
export function Auth({onSignedIn,initialError=""}:{onSignedIn:()=>void;initialError?:string}){
  const [mode,setMode]=useState<"signin"|"signup"|"recovery">("signin"),[email,setEmail]=useState(""),[password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(initialError),[message,setMessage]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");setMessage("");try{const r=await api<{confirmationRequired?:boolean}>("/api/auth",{action:mode,email,password});if(mode==="recovery")setMessage("If that account exists, a reset link will arrive by email. Open it in this browser.");else if(r.confirmationRequired)setMessage("Check your email to confirm your account. Open the link in this browser to finish signing in.");else onSignedIn();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <main className="us-auth"><section className="us-auth-story"><a className="us-brand" href="/" aria-label="Unsite home"><span className="us-symbol">u</span>unsite<span className="us-word-dot">.</span></a><div className="us-auth-copy"><span className="us-eyebrow">Your material, ready for agents</span><h1>Your knowledge.<br/>A presence<br/>of its own.</h1><p>Bring documents, ideas, research, or collected work. Organize the context and choose what agents can access.</p><div className="us-auth-art" aria-hidden="true"><div><FileText size={20}/><span>Your sources</span><span className="us-art-line"/></div><div><Check size={20}/><span>Your approval</span><span className="us-art-line"/></div><div><Braces size={20}/><span>Your presence</span><span className="us-art-dot"/></div></div></div><small>Your originals stay private. You choose what goes live.</small></section><section className="us-auth-form"><span className="us-eyebrow">Your Unsite workspace</span><h2>{mode==="signin"?"Welcome back.":mode==="signup"?"Make room for your ideas.":"Let’s get you back in."}</h2><p>{mode==="signin"?"Sign in to pick up where you left off.":mode==="signup"?"Create a private workspace for whatever knowledge you want to share.":"We’ll email you a link to reset your password."}</p><form onSubmit={submit}><Field label="Email address">{id=><Input id={id} type="email" autoComplete="email" required value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com"/>}</Field>{mode!=="recovery"&&<Field label="Password" hint={mode==="signup"?"At least 12 characters.":undefined}>{id=><Input id={id} type="password" autoComplete={mode==="signup"?"new-password":"current-password"} minLength={mode==="signup"?12:1} required value={password} onChange={e=>setPassword(e.target.value)}/>}</Field>}<ErrorNotice message={error}/>{message&&<div className="us-success" role="status">{message}</div>}<Action type="submit" disabled={busy}>{busy?<Busy label="One moment…"/>:mode==="signin"?<>Sign in<ArrowRight size={16}/></>:mode==="signup"?"Create account":"Send reset link"}</Action></form><div className="us-auth-links">{mode==="signup"&&message&&<button disabled={busy} onClick={async()=>{setBusy(true);setError("");try{await api("/api/auth",{action:"resend",email});setMessage("A fresh confirmation link has been requested. Check your inbox and spam folder.");}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>Resend confirmation email</button>}{mode==="signin"?<><button onClick={()=>{setMode("signup");setError("");setMessage("");}}>New here? Create an account</button><button onClick={()=>{setMode("recovery");setError("");setMessage("");}}>Forgot password?</button></>:<button onClick={()=>{setMode("signin");setError("");setMessage("");}}>Back to sign in</button>}</div><div className="us-auth-private"><LockKeyhole size={15}/>Private by default. Published by you.</div></section></main>;
}
export function Recover(){
  const [password,setPassword]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[done,setDone]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await api("/api/auth",{action:"password",password});setDone(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <main className="unsite-console us-centered"><section className="us-card us-account-card"><div className="us-brand"><span className="us-symbol">u</span>unsite.</div><h1>{done?"Password updated.":"Choose a new password."}</h1>{done?<a className="us-link" href="/">Open your workspace<ArrowRight size={16}/></a>:<form onSubmit={submit}><Field label="New password" hint="Use at least 12 characters.">{id=><Input id={id} required minLength={12} type="password" autoComplete="new-password" value={password} onChange={e=>setPassword(e.target.value)}/>}</Field><ErrorNotice message={error}/><Action type="submit" disabled={busy}>{busy?<Busy/>:"Update password"}</Action></form>}</section></main>;
}
