"use client";
import {EvidencePassage} from "./collection-preparation";
import {useEffect,useRef,useState,type FormEvent} from "react";
import {BookOpen,Check,CheckCheck,FileText,Plus,Quote,Trash2} from "lucide-react";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import type {Candidate,KnowledgeFields,KnowledgeRecord,RecordKind,SpaceState} from "@/lib/production/types";
import {Action,useApi,Busy,Choice,Empty,ErrorNotice,External,Field,Modal,Pill,stamp,type Command} from "./shared";
import {ContextEditor,LinksEditor,ReadingContext} from "./context-editor";
import {contextOf,entryType,combineMaterial,differingFields,relationLabels,type KnowledgeContext,type KnowledgeLink,type Comparable} from "@/lib/production/knowledge";
import type {Snapshot} from "@/lib/production/release";
type RecordDetail=KnowledgeRecord&{links?:KnowledgeLink[];history?:{candidate_id:string;record_revision:number;recorded_at:string}[];evidence?:Pick<Candidate,"id"|"title"|"evidence"|"source_version_id">[]};
type Entry=Pick<KnowledgeRecord,"title"|"kind"|"text"|"fields">&{public_source_url?:string|null;context?:KnowledgeContext;links?:KnowledgeLink[]};
function useEntry(entry:Entry,entries:{id:string;title:string}[]=[],selfId?:string){
  const [context,setContext]=useState(contextOf(entry.context)),[aliases,setAliases]=useState((entry.context?.aliases||[]).join(", ")),[topics,setTopics]=useState((entry.context?.topics||[]).join(", ")),[links,setLinks]=useState<KnowledgeLink[]>(entry.links||[]);
  const [title,setTitle]=useState(entry.title),[text,setText]=useState(entry.text),[kind,setKind]=useState<RecordKind>(entry.kind),[publicUrl,setPublicUrl]=useState(entry.public_source_url||"");
  const [fields,setFields]=useState(Object.entries(entry.fields).map(([key,value])=>({id:crypto.randomUUID(),key,type:value===null?"unknown":typeof value==="number"?"number":typeof value==="boolean"?"boolean":"text",value:value===null?"":String(value)})));
  function payload(){const out:KnowledgeFields={};for(const f of fields){if(!f.key.trim())throw new Error("Give every structured field a name, or remove the empty row.");if(Object.hasOwn(out,f.key.trim()))throw new Error("Field names must be unique.");if(["__proto__","prototype","constructor"].includes(f.key.trim()))throw new Error("Choose a different field name.");if(f.type==="number"&&(!f.value.trim()||!Number.isFinite(Number(f.value))))throw new Error("Enter a valid number for "+f.key+".");out[f.key.trim()]=f.type==="unknown"?null:f.type==="number"?Number(f.value):f.type==="boolean"?f.value==="true":f.value;}if(links.some(l=>!l.target_id))throw new Error("Choose a target for every relationship.");const tags=(v:string)=>[...new Set(v.split(",").map(x=>x.trim()).filter(Boolean))];return {title,kind,text,fields:out,context:{...context,aliases:tags(aliases),topics:tags(topics)},links,public_source_url:publicUrl};}
  const form=<><Field label="Title">{id=><Input id={id} required maxLength={200} value={title} onChange={e=>setTitle(e.target.value)}/>}</Field><Field label="Content" hint="Keep the complete explanation, sequence, and qualifications agents should read after publication.">{id=><Textarea id={id} rows={7} required maxLength={40000} value={text} onChange={e=>setText(e.target.value)}/>}</Field><div className="us-fields-heading"><strong>Structured fields</strong><button type="button" disabled={fields.length>=30} onClick={()=>setFields(v=>[...v,{id:crypto.randomUUID(),key:"",value:"",type:"text"}])}><Plus size={14}/>Add field</button></div><p className="us-small us-muted">Explicit details such as ownership, dates, status, or scope.</p>{fields.map((f,index)=><div className="us-structured-field" key={f.id}><Input aria-label={`Field ${index+1} name`} placeholder="Field name" maxLength={100} value={f.key} onChange={e=>setFields(v=>v.map(x=>x.id===f.id?{...x,key:e.target.value}:x))}/><Choice label={`Field ${index+1} type`} value={f.type} onChange={type=>setFields(v=>v.map(x=>x.id===f.id?{...x,type,value:type==="boolean"?"true":x.value}:x))} items={[{value:"text",label:"Text"},{value:"number",label:"Number"},{value:"boolean",label:"Yes / no"},{value:"unknown",label:"Unknown"}]}/>{f.type==="boolean"?<Choice label={`Field ${index+1} value`} value={f.value} onChange={value=>setFields(v=>v.map(x=>x.id===f.id?{...x,value}:x))} items={[{value:"true",label:"Yes"},{value:"false",label:"No"}]}/>:<Input aria-label={`Field ${index+1} value`} type={f.type==="number"?"number":"text"} step="any" disabled={f.type==="unknown"} value={f.type==="unknown"?"":f.value} maxLength={4000} placeholder="Value" onChange={e=>setFields(v=>v.map(x=>x.id===f.id?{...x,value:e.target.value}:x))}/>}<button type="button" className="us-icon-button" aria-label={`Remove ${f.key||"field"}`} onClick={()=>setFields(v=>v.filter(x=>x.id!==f.id))}><Trash2 size={16}/></button></div>)}<ContextEditor value={context} onChange={setContext} aliases={aliases} setAliases={setAliases} topics={topics} setTopics={setTopics}/><LinksEditor value={links} onChange={setLinks} entries={entries} selfId={selfId}/><Field label="Public source link (optional)" hint="Only add a link you want to disclose. Private uploads and their storage URLs are never included.">{id=><Input id={id} type="url" placeholder="https://…" value={publicUrl} onChange={e=>setPublicUrl(e.target.value)}/>}</Field></>;
  function loadExisting(next:Entry,combine=false){
    const material=combine?combineMaterial(next,entry):{text:next.text,context:contextOf(next.context)};
    setTitle(next.title);setKind(next.kind);setText(material.text);setPublicUrl(next.public_source_url||"");
    setContext(material.context);setAliases(material.context.aliases.join(", "));setTopics(material.context.topics.join(", "));
    setFields(Object.entries(next.fields).map(([key,value])=>({id:crypto.randomUUID(),key,type:value===null?"unknown":typeof value==="number"?"number":typeof value==="boolean"?"boolean":"text",value:value===null?"":String(value)})));
    setLinks(next.links||[]);
  }
  return {form,payload,loadExisting,setLinks};
}
function RecordEditor({record,entries,onClose,command,canEdit}:{record:RecordDetail|null;entries:{id:string;title:string}[];onClose:()=>void;command:Command;canEdit:boolean}){
  const {form,payload}=useEntry(record||{title:"",text:"",kind:"general",fields:{}} ,entries,record?.id),[busy,setBusy]=useState(false),[error,setError]=useState(""),[active,setActive]=useState(record?.active??true),request=useRef(crypto.randomUUID());
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await command(record?"edit_record":"create_record",{...payload(),...(record?{record_id:record.id,revision:record.revision,active}:{request_id:request.current})});onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal open onClose={()=>!busy&&onClose()} title={record?"Edit knowledge":"Add a knowledge entry"} description="Save approved information to your knowledge. Your live publication changes only when you publish a release." wide><form onSubmit={submit}><fieldset disabled={!canEdit||busy}>{form}{record&&<label className="us-check"><input type="checkbox" checked={active} onChange={e=>setActive(e.target.checked)}/>Include this entry in the next publication</label>}</fieldset>{!!record?.history?.length&&<details className="us-evidence us-evidence-history"><summary>Source review history · {record.history.length} accepted suggestions</summary><p className="us-small us-muted">Evidence retained from accepted suggestions. Later edits may go beyond these passages. This history stays private.</p>{record.history.map(h=>{const source=record.evidence?.find(e=>e.id===h.candidate_id);return <section key={h.candidate_id+":"+h.record_revision}><h3>{source?.title||"Accepted source suggestion"}</h3><small>Accepted with entry revision {h.record_revision} · {stamp(h.recorded_at)}</small>{source?.evidence.map((e,i)=><figure key={i}><blockquote>{e.quote}</blockquote><figcaption>{e.locator}</figcaption></figure>)}</section>;})}</details>}<ErrorNotice message={error}/><div className="us-modal-actions"><small className="us-muted">{record?`Revision ${record.revision}`:"Manually entered · approved by you"}</small>{canEdit&&<Action type="submit" disabled={busy}>{busy?<Busy label="Saving…"/>:"Save to knowledge"}</Action>}</div></form></Modal>;
}
export function Knowledge({state,command,loadMore,canEdit}:{state:SpaceState;command:Command;loadMore:()=>Promise<void>;canEdit:boolean}){
  const api=useApi();
  const [edit,setEdit]=useState<RecordDetail|null|undefined>(),[query,setQuery]=useState(""),[kind,setKind]=useState("all"),[loading,setLoading]=useState(false),[error,setError]=useState("");
  const [entries,setEntries]=useState<{id:string;title:string}[]>([]);
  useEffect(()=>{let alive=true;api<{snapshot:Snapshot}>("/api/app/knowledge?space="+state.space.id).then(d=>alive&&setEntries(d.snapshot.records)).catch(e=>alive&&setError(e.message));return()=>{alive=false;};},[api,state.space.id,state.space.content_revision]);
  async function openRecord(r:KnowledgeRecord){setLoading(true);try{const d=await api<{record:KnowledgeRecord;links:KnowledgeLink[];history:RecordDetail["history"];evidence:RecordDetail["evidence"]}>("/api/app/record?id="+r.id);setEdit({...d.record,links:d.links,history:d.history,evidence:d.evidence});}catch(e){setError((e as Error).message);}finally{setLoading(false);}}
  const types=[...new Map(state.records.map(r=>["type:"+entryType(r).normalize("NFKC").toLowerCase(),entryType(r)])).entries()].sort((a,b)=>a[1].localeCompare(b[1]));
  const list=state.records.filter(r=>(kind==="all"||"type:"+entryType(r).normalize("NFKC").toLowerCase()===kind)&&JSON.stringify([r.title,r.text,r.fields,r.context]).toLowerCase().includes(query.toLowerCase()));
  return <><div className="us-section-heading"><div><span className="us-eyebrow">Approved by you</span><h1>Knowledge</h1><p>Your approved material, with the context agents need to understand it.</p></div>{canEdit&&<Action onClick={()=>setEdit(null)}><Plus size={17}/>Add entry</Action>}</div><div className="us-toolbar"><Input aria-label="Search knowledge" placeholder="Search loaded entries…" value={query} onChange={e=>setQuery(e.target.value)}/><Choice label="Filter loaded content types" value={kind} onChange={setKind} items={[{value:"all",label:"All content types"},...types.map(([value,label])=>({value,label}))]}/><span className="us-muted us-small">{state.recordCount} total entries</span></div>{list.length?<div className="us-knowledge-grid">{list.map(r=><button className="us-knowledge-card" key={r.id} onClick={()=>void openRecord(r)} disabled={loading}><div className="us-between"><Pill>{entryType(r)}</Pill>{r.active?<Check size={16} className="us-green"/>:<Pill tone="amber">Excluded</Pill>}</div><h3>{r.title}</h3><ReadingContext value={r.context}/><p>{r.context?.summary||r.text}</p>{r.context?.topics.length>0&&<div className="us-topic-labels">{r.context.topics.map(t=><Pill key={t}>{t}</Pill>)}</div>}{Object.keys(r.fields).length>0&&<div className="us-field-preview">{Object.entries(r.fields).slice(0,3).map(([k,v])=><span key={k}><small>{k}</small><strong>{String(v)}</strong></span>)}</div>}<footer><span>{r.candidate_id?"From reviewed source":"Manually entered"}</span><span>v{r.revision}</span></footer></button>)}</div>:<Empty icon={<BookOpen size={30}/>} title={query||kind!=="all"?"No matching entries":"Build a clear picture"} description="Accept prepared suggestions in Review, or add information directly. Only your approved knowledge is eligible for publication." action={canEdit?<Action onClick={()=>setEdit(null)}><Plus size={16}/>Add an entry</Action>:undefined}/>}{state.records.length<state.recordCount&&<Action secondary disabled={loading} onClick={async()=>{setLoading(true);try{await loadMore();}catch(e){setError((e as Error).message);}finally{setLoading(false);}}}>{loading?<Busy/>:`Load more (${state.records.length} of ${state.recordCount})`}</Action>}<ErrorNotice message={error}/>{edit!==undefined&&<RecordEditor key={edit?.id||"new"} record={edit} entries={entries} command={command} onClose={()=>setEdit(undefined)} canEdit={canEdit}/>}</>;
}
function CandidateReview({candidate,state,command,onClose}:{candidate:Candidate;state:SpaceState;command:Command;onClose:()=>void}){
  const api=useApi();
  const [catalog,setCatalog]=useState<Snapshot["records"]>([]),[comparisons,setComparisons]=useState<(Comparable&{origin:"record"|"candidate";similarity:number})[]>([]),[target,setTarget]=useState("new"),[targetRecord,setTargetRecord]=useState<(KnowledgeRecord&{links:KnowledgeLink[]})|null>(null),[busy,setBusy]=useState(false),[loading,setLoading]=useState(true),[error,setError]=useState("");
  const [verificationReviewed,setVerificationReviewed]=useState(false);
  const {form,payload,loadExisting,setLinks}=useEntry(candidate,catalog,target==="new"?undefined:target);
  const source=state.sources.find(s=>s.id===state.versions.find(v=>v.id===candidate.source_version_id)?.source_id);
  useEffect(()=>{let alive=true;Promise.all([api<{snapshot:Snapshot}>("/api/app/knowledge?space="+state.space.id),api<{matches:typeof comparisons}>("/api/app/comparisons?candidate="+candidate.id)]).then(([data,comp])=>{if(alive){setCatalog(data.snapshot.records);setComparisons(comp.matches);}}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setLoading(false));return()=>{alive=false;};},[api,candidate.id,state.space.id]);
  async function chooseTarget(id:string){if(busy)return;setTarget(id);setTargetRecord(null);setError("");if(id==="new"){setLinks([]);return;}setBusy(true);try{const d=await api<{record:KnowledgeRecord;links:KnowledgeLink[]}>("/api/app/record?id="+id);setTargetRecord({...d.record,links:d.links});setLinks(d.links);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  async function decide(decision:"accept"|"exclude"){setBusy(true);setError("");try{if(decision==="accept"&&target!=="new"&&!targetRecord)throw new Error("Load the existing entry before saving an update.");await command("review_candidate",{...(decision==="exclude"?{title:candidate.title,text:candidate.text,kind:candidate.kind,fields:candidate.fields}:payload()),candidate_id:candidate.id,revision:candidate.revision,decision,verification_reviewed:verificationReviewed,...(targetRecord?{record_id:targetRecord.id,record_revision:targetRecord.revision}:{})});onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal open onClose={()=>!busy&&onClose()} title="Review prepared knowledge" description="Compare related material, preserve the context, and decide what an agent should be able to read." wide><form onSubmit={e=>{e.preventDefault();void decide("accept");}}>
    {candidate.collection_run_id&&<section className="us-comparisons"><div className="us-between"><h3>Collection proposal</h3><Pill tone={candidate.verification?.verdict==="supported"?"green":"amber"}>{candidate.verification?.verdict==="supported"?"Evidence check passed":candidate.verification?.verdict==="unsupported"?"Evidence does not support this wording":"Needs your judgment"}</Pill></div><p>{candidate.change_reason}</p><p className="us-small us-muted">The verifier assesses the supplied evidence. This does not establish independent truth or approve publication.</p>{candidate.verification?.issues.map((issue,i)=><div className="us-notice" key={i}>{issue}</div>)}{candidate.suggested_record_id&&<button className="us-link" type="button" disabled={busy||loading} onClick={()=>void chooseTarget(candidate.suggested_record_id!)}>Compare with the suggested existing entry</button>}{candidate.suggested_record_id===targetRecord?.id&&candidate.suggested_record_revision!==targetRecord?.revision&&<div className="us-notice">This entry changed after the collection started. Compare your current entry below before approving a replacement.</div>}{candidate.verification?.verdict!=="supported"&&<label className="us-check"><input type="checkbox" disabled={busy} checked={verificationReviewed} onChange={e=>setVerificationReviewed(e.target.checked)}/><span>I have reviewed these concerns and corrected the proposed content where needed.</span></label>}</section>}
    {loading?<Busy label="Finding related knowledge…"/>:comparisons.length>0&&<section className="us-comparisons"><h3>Potential overlap</h3><p className="us-small us-muted">Names and aliases suggest these comparisons. Check whether they describe the same subject before combining them.</p>{comparisons.map(match=>{const differences=differingFields(candidate,match);return <article key={match.origin+match.id}><div className="us-between"><strong>{match.title}</strong><Pill>{match.origin==="record"?"Approved knowledge":"Another suggestion"}</Pill></div><ReadingContext value={match.context}/><p>{match.context?.summary||match.text.slice(0,300)}</p>{differences.length>0&&<table className="us-comparison-table"><thead><tr><th>Field</th><th>This suggestion</th><th>Existing value</th></tr></thead><tbody>{differences.map(d=><tr key={d.key}><th>{d.key}</th><td>{String(d.incoming)}</td><td>{String(d.existing)}</td></tr>)}</tbody></table>}{match.origin==="record"&&<button type="button" className="us-link" disabled={busy} onClick={()=>void chooseTarget(match.id)}>Review as an update to this entry</button>}</article>;})}</section>}
    <fieldset disabled={busy||loading}><Field label="Save this as">{()=> <Choice label="Create or update knowledge" value={target} onChange={id=>void chooseTarget(id)} items={[{value:"new",label:"A new knowledge entry"},...catalog.map(r=>({value:r.id,label:"Update: "+r.title}))]}/>}</Field></fieldset>
    {targetRecord&&<div className="us-comparisons"><h3>Preserve your existing decisions</h3><ReadingContext value={targetRecord.context}/><p>{targetRecord.text}</p><div className="us-inline-actions"><button type="button" onClick={()=>loadExisting(targetRecord)}>Start with existing entry</button><button type="button" onClick={()=>loadExisting(targetRecord,true)}>Combine both descriptions</button></div><p className="us-small us-muted">These choices retain existing structured values. Combining keeps each perspective in an attributed section. Review the combined summary, labels, and details below. The final entry replaces the draft only after approval.</p></div>}
    <div className="us-review-split"><section><fieldset disabled={busy||loading}>{form}</fieldset></section><aside className="us-evidence"><span className="us-eyebrow"><Quote size={15}/>Source evidence</span><h3>{source?.title||"Original source"}</h3><Pill>Private original</Pill>{candidate.evidence.map((e,i)=>{const v=state.versions.find(v=>v.id===e.source_version_id),s=state.sources.find(s=>s.id===v?.source_id);return <EvidencePassage key={i} evidence={e} label={(s?.title||"Source")+(v?" · v"+v.version:"")}/>;})}{candidate.suggested_links?.length>0&&<section><h3>Suggested relationships</h3>{candidate.suggested_links.map((link,i)=><figure key={i}><strong>{relationLabels[link.relation]}: {link.target_title}</strong><blockquote>{link.quote}</blockquote></figure>)}<p className="us-small us-muted">Choose the matching approved entries in Relationships. Suggested names do not establish identity.</p></section>}{source?.origin_url&&<External href={source.origin_url}>Read source page</External>}{candidate.warnings.map((w,i)=><div className="us-notice" key={i}>{w}</div>)}<p className="us-small us-muted">Quotes match the source text. Check that they support the complete wording and its qualifications.</p></aside></div><ErrorNotice message={error}/><div className="us-modal-actions"><Action secondary disabled={busy} onClick={()=>decide("exclude")}>Exclude suggestion</Action><Action type="submit" disabled={busy||loading}>{busy?<Busy label="Saving decision…"/>:<><Check size={17}/>Approve to knowledge</>}</Action></div></form></Modal>;
}
export function Review({state,command,loadMore,canEdit}:{state:SpaceState;command:Command;loadMore:()=>Promise<void>;canEdit:boolean}){
  const [selected,setSelected]=useState<Candidate|undefined>(),[busy,setBusy]=useState(false),[error,setError]=useState("");
  return <><div className="us-section-heading"><div><span className="us-eyebrow">You have the final say</span><h1>Review <span className="us-heading-count">{state.candidateCount}</span></h1><p>Source-supported suggestions, ready for your judgment.</p></div><Pill tone="green"><ShieldLabel/></Pill></div>{state.candidates.length?<div className="us-review-list">{state.candidates.map(c=>{const source=state.sources.find(s=>s.id===state.versions.find(v=>v.id===c.source_version_id)?.source_id);return <div className="us-review-row us-card" key={c.id}><div className="us-review-category"><Pill>{entryType(c)}</Pill><small>{stamp(c.created_at)}</small></div><div><h3>{c.title}</h3><ReadingContext value={c.context}/><p>{c.text}</p><span className="us-small us-muted"><FileText size={14}/>{c.collection_run_id?"Collection preparation":source?.title||"Imported source"} · {c.evidence.length} supporting quote{c.evidence.length===1?"":"s"}</span>{c.warnings.length>0&&<Pill tone="amber">{c.warnings.length} point{c.warnings.length===1?"":"s"} to check</Pill>}</div>{canEdit&&<Action secondary onClick={()=>setSelected(c)}>Review</Action>}</div>;})}</div>:<Empty icon={<CheckCheck size={31}/>} title="Nothing waiting on you" description={state.sources.length?"New suggestions appear here as your sources are prepared. Your existing approved knowledge stays intact.":"Add sources to prepare your first suggestions. Each one will arrive with the text that supports it."}/>}{state.candidates.length<state.candidateCount&&<Action secondary disabled={busy} onClick={async()=>{setBusy(true);try{await loadMore();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}}>{busy?<Busy/>:"Load more suggestions"}</Action>}<ErrorNotice message={error}/>{selected&&<CandidateReview key={selected.id} candidate={selected} state={state} command={command} onClose={()=>setSelected(undefined)}/>}</>;
}
function ShieldLabel(){return <><Check size={13}/>Nothing publishes automatically</>;}
