"use client";
import {useState} from "react";
import {Input} from "@/components/ui/input";
import {Action,Busy,Choice,Empty,ErrorNotice,External,Field,Modal,Pill,stamp,saveFile} from "./shared";
import {Globe} from "./icons";
import {claimState,hostingReady,type PresenceState} from "@/lib/production/presence";
import {publicationReadiness} from "@/lib/production/readiness";
import type {RuntimeStatus,SpaceState} from "@/lib/production/types";

type Props={state:SpaceState;data:PresenceState;status:RuntimeStatus|null;isOwner:boolean;canEdit:boolean;sample:boolean;error?:string;run:(action:string,payload:Record<string,unknown>)=>Promise<boolean>};
type Panel="semantic"|"index"|"host"|"discovery"|null;
export function Readiness({state,data,canEdit,sample,run}:Props){
  const checks=publicationReadiness(state,data),[busy,setBusy]=useState(false);
  return <><div className="us-subheading"><h2>Publication readiness</h2><Action secondary onClick={()=>saveFile("unsite-readiness.json",{checked_at:new Date().toISOString(),release_id:state.space.active_release_id,checks,note:"Service checks, not an AI ranking or independent factual assessment."})}>Export checks</Action></div>
    <p className="us-small us-muted">Each check explains what is known and what needs attention. These results do not measure AI search rank.</p>
    <div className="us-card us-geo-list">{checks.map(c=><article key={c.id}><div className="us-between"><h3>{c.label}</h3><Pill tone={c.status==="ready"?"green":c.status==="attention"?"amber":"neutral"}>{c.status.replaceAll("_"," ")}</Pill></div><p>{c.detail}</p></article>)}</div>
    {canEdit&&<div className="us-inline-actions"><Action secondary disabled={sample||busy||!state.space.active_release_id} onClick={async()=>{setBusy(true);try{await run("check_delivery",{request_id:crypto.randomUUID()});}finally{setBusy(false);}}}>Check API and MCP</Action><Action secondary disabled={sample||busy||!state.space.active_release_id} onClick={async()=>{setBusy(true);try{await run("check_resources",{});}finally{setBusy(false);}}}>Check resource links</Action></div>}
  </>;
}
export function ResourceHealth({data,canEdit,sample,run,state}:Props){
  const [busy,setBusy]=useState(false),checks=data.resource_checks||[];
  return <><div className="us-subheading"><h2>Published resource health</h2>{canEdit&&<Action secondary disabled={sample||busy||!state.space.active_release_id} onClick={async()=>{setBusy(true);try{await run("check_resources",{});}finally{setBusy(false);}}}>Check links</Action>}</div><p className="us-small us-muted">Daily checks inspect published links and their declared format. Resource contents are not downloaded or retained. Draft links are checked after publication.</p>
    {checks.length?<div className="us-card us-geo-list">{checks.map(c=><article key={c.id}><div className="us-between"><h3>{c.title}</h3><Pill tone={c.result?.ok&&!c.result.warning?"green":c.result||c.status==="failed"?"amber":"neutral"}>{["queued","running"].includes(c.status)?c.status:c.result?.ok?c.result.warning?"Format warning":"Available":"Needs attention"}</Pill></div><p className="us-small us-muted">{c.checked_at?stamp(c.checked_at):"Not checked yet"}{c.result?.http_status?" · HTTP "+c.result.http_status:""}</p>{(c.error_message||c.result?.warning)&&<p>{c.error_message||c.result?.warning}</p>}<External href={c.url}>Open published resource</External></article>)}</div>:<p className="us-small us-muted">No published resource checks yet.</p>}
  </>;
}
export function LaunchSettings(props:Props){
  const {state,data,status,isOwner,sample,run}=props,[panel,setPanel]=useState<Panel>(null),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const settings=data.semantic?.settings||{enabled:false,daily_query_limit:100,revision:0,query_requests:0},index=data.semantic?.indexes.find(i=>i.release_id===state.space.active_release_id),host=data.hosting,ready=hostingReady(host);
  async function action(name:string,p:Record<string,unknown>={},close=false){setBusy(true);setError("");try{if(await run(name,p)){if(close)setPanel(null);}}finally{setBusy(false);}}
  return <>
    <div className="us-subheading"><h2>Semantic retrieval</h2>{isOwner&&<Action secondary onClick={()=>setPanel("semantic")}>Configure</Action>}</div>
    <div className="us-card us-geo-card"><div className="us-between"><h3>Search by meaning</h3><Pill>{settings.enabled?"Enabled":"Off"}</Pill></div><p>Combine keyword matches with semantic similarity while keeping the full approved record available for citation.</p><p className="us-small us-muted">OpenAI · text-embedding-3-small · {settings.daily_query_limit} query requests per day · {settings.usage_day===new Date().toISOString().slice(0,10)?settings.query_requests:0} used today</p>
      {!status?.embeddings&&!sample&&<p className="us-small">The embedding provider is not confirmed ready. Configure OpenAI and the worker connection before indexing.</p>}
      {index?<><p>{index.ready_chunks} of {index.total_chunks} passages indexed for the current release.</p>{index.error_message&&<p>{index.error_message}</p>}</>:<p className="us-small us-muted">{state.space.active_release_id?"The current release has not been authorized for semantic indexing.":"Publish an approved release before indexing."}</p>}
      {isOwner&&<Action secondary disabled={!settings.enabled||!state.space.active_release_id||!!index?.pending_chunks||busy} onClick={()=>setPanel("index")}>{index?.blocked_chunks?"Review and retry indexing":index?.ready_chunks===index?.total_chunks&&index?"Review index":"Index current release"}</Action>}
      <p className="us-small us-muted">New releases require their own authorization. External agents explicitly authorize sending their query to OpenAI; ordinary search continues to use keywords.</p>
    </div>
    <div className="us-subheading"><h2>Custom hostname</h2>{isOwner&&<Action secondary onClick={()=>setPanel("host")}>{host?"Change hostname":"Connect hostname"}</Action>}</div>
    {host?<div className="us-card us-geo-card"><div className="us-between"><h3>{host.hostname}</h3><Pill tone={ready?"green":"neutral"}>{ready?"Connected":host.status==="disabled"?"Disabled":"Connection needed"}</Pill></div><p className="us-small us-muted">{host.checked_at?"Last checked "+stamp(host.checked_at):"HTTPS connection has not been verified."}</p>{host.error_message&&<p>{host.error_message}</p>}<p>Add this exact hostname to the Unsite project in Vercel, then copy the DNS record shown there into your domain settings. HTTPS and DNS proof are checked before this address becomes canonical.</p><div className="us-inline-actions"><External href="https://vercel.com/jarah-1573/unsite/settings/domains">Open hosting settings</External>{ready&&<External href={"https://"+host.hostname}>Open publication</External>}{isOwner&&<><Action secondary disabled={busy||sample||host.status==="disabled"} onClick={()=>void action("check_host")}>Check connection</Action><Action secondary disabled={busy||host.status==="disabled"} onClick={()=>void action("disable_host")}>Disable hostname</Action></>}</div></div>:<Empty icon={<Globe size={26}/>} title="Publish at your own address" description="Verify a hostname in Identity, then connect it here. A subdomain such as knowledge.example.com can keep your existing website in place."/>}
    <div className="us-subheading"><h2>Search engines</h2>{isOwner&&<Action secondary disabled={!ready&&!sample} onClick={()=>setPanel("discovery")}>Configure discovery</Action>}</div>
    <div className="us-card us-geo-card"><h3>Verification and update notifications</h3><p>Add Google Search Console or Bing verification tokens for your connected hostname. IndexNow can notify participating search engines when approved pages change or are removed.</p><p className="us-small us-muted">{data.discovery?.indexnow_enabled?"IndexNow notifications are enabled.":"IndexNow notifications are off."} A received submission does not confirm indexing or AI citation.</p>{host&&<><code className="us-geo-code">{"https://"+host.hostname+"/sitemap.xml"}</code><div className="us-geo-links"><External href={"https://search.google.com/search-console?resource_id="+encodeURIComponent("https://"+host.hostname+"/")}>Google Search Console</External><External href="https://www.bing.com/webmasters/">Bing Webmaster Tools</External></div></>}{isOwner&&data.discovery?.indexnow_enabled&&<Action secondary disabled={sample||busy||!ready} onClick={()=>void action("submit_discovery")}>Submit current publication</Action>}</div>
    {!!data.submissions?.length&&<div className="us-card us-geo-list">{data.submissions.map(s=><article key={s.id}><div className="us-between"><strong>{stamp(s.created_at)}</strong><Pill>{s.result?.state.replaceAll("_"," ")||s.status}</Pill></div>{s.result&&<p>{s.result.url_count} public URLs · HTTP {s.result.http_status}</p>}{s.error_message&&<p>{s.error_message}</p>}{s.next_at&&<p className="us-small us-muted">Next attempt: {stamp(s.next_at)}</p>}</article>)}</div>}
    {panel&&<Modal open onClose={()=>!busy&&setPanel(null)} title={panel==="semantic"?"Semantic search settings":panel==="index"?"Authorize this release":panel==="host"?"Connect a hostname":"Search-engine setup"} description="Review these settings before saving.">
      {panel==="semantic"&&<SemanticForm value={settings} busy={busy} onSave={p=>void action("save_semantic",p,true)}/>}
      {panel==="index"&&<IndexForm releaseId={state.space.active_release_id!} index={index} busy={busy} sample={sample} onSave={p=>void action("index_release",p,true)}/>}
      {panel==="host"&&<HostForm data={data} busy={busy} sample={sample} onSave={p=>void action("register_host",p,true)}/>}
      {panel==="discovery"&&<DiscoveryForm data={data} busy={busy} sample={sample} onSave={p=>void action("save_discovery",p,true)}/>}
      <ErrorNotice message={error||props.error||""}/>
    </Modal>}
  </>;
}
function SemanticForm({value,busy,onSave}:{value:{enabled:boolean;daily_query_limit:number;revision:number};busy:boolean;onSave:(p:Record<string,unknown>)=>void}){
  const [enabled,setEnabled]=useState(value.enabled),[limit,setLimit]=useState(value.daily_query_limit),[consent,setConsent]=useState(false);
  return <form className="us-form" onSubmit={e=>{e.preventDefault();onSave({revision:value.revision,enabled,daily_query_limit:limit,...(enabled?{consent:"openai-public-embeddings-v1"}:{})});}}><label className="us-check"><input type="checkbox" checked={enabled} onChange={e=>setEnabled(e.target.checked)}/>Enable semantic retrieval</label><Field label="Maximum semantic query requests per day" hint="A limit from 1 to 1,000 per workspace. Failed provider requests count toward this limit.">{id=><Input id={id} type="number" min={1} max={1000} required value={limit} onChange={e=>setLimit(Number(e.target.value))}/>}</Field><p>Indexing sends approved publication passages to OpenAI. Semantic queries send the requesting agent’s query to OpenAI only with its explicit consent. Provider charges may apply. Private uploads, drafts, and saved test questions are excluded.</p><p>Each release requires separate indexing approval. Disabling this setting stops new indexing and semantic queries.</p>{enabled&&<label className="us-check"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>I authorize this provider and the daily query limit.</label>}<div className="us-modal-actions"><Action type="submit" disabled={busy||enabled&&!consent}>{busy?<Busy/>:"Save settings"}</Action></div></form>;
}
function IndexForm({releaseId,index,busy,sample,onSave}:{releaseId:string;index:{input_characters:number;blocked_chunks:number;ready_chunks:number;total_chunks:number}|undefined;busy:boolean;sample:boolean;onSave:(p:Record<string,unknown>)=>void}){
  const [consent,setConsent]=useState(false),[retry,setRetry]=useState(false),complete=Boolean(index&&index.ready_chunks===index.total_chunks);
  return <form className="us-form" onSubmit={e=>{e.preventDefault();onSave({release_id:releaseId,request_id:crypto.randomUUID(),consent:"openai-public-embeddings-v1",retry_acknowledged:retry});}}><p>Send the current release’s approved text, context, and fields to OpenAI to build its semantic index. This uses text-embedding-3-small with 512 dimensions, in batches of up to 16 passages.</p><code className="us-geo-code">{releaseId}</code><p className="us-small us-muted">{index?`${index.input_characters.toLocaleString()} public characters in this release.`:"Up to 2 million public characters per release; larger releases are rejected before a provider call."} Each passage is limited to 2,000 characters. Provider usage is recorded when returned.</p>{index&&index.blocked_chunks>0&&<label className="us-check"><input type="checkbox" required checked={retry} onChange={e=>setRetry(e.target.checked)}/>An earlier attempt may already have been charged. I authorize retrying its unfinished passages.</label>}{!complete&&<label className="us-check"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>I approve sending this public release to OpenAI for indexing.</label>}{sample&&<p className="us-notice">The sample cannot contact an embedding provider.</p>}<div className="us-modal-actions"><Action type="submit" disabled={sample||complete||busy||!consent||!!index?.blocked_chunks&&!retry}>{complete?"Index complete":busy?<Busy/>:"Authorize indexing"}</Action></div></form>;
}
function HostForm({data,busy,sample,onSave}:{data:PresenceState;busy:boolean;sample:boolean;onSave:(p:Record<string,unknown>)=>void}){
  const choices=data.claims.filter(c=>claimState(c)==="verified"),[claim,setClaim]=useState(choices[0]?.id||"");
  return <form className="us-form" onSubmit={e=>{e.preventDefault();onSave({claim_id:claim,revision:data.hosting?.revision||0});}}><p>Select a hostname with current DNS ownership proof. After saving, add it to the Unsite Vercel project and configure the DNS record shown there. Unsite checks the HTTPS connection before switching canonical URLs.</p>{choices.length?<Field label="Verified hostname">{()=> <Choice label="Verified hostname" value={claim} onChange={setClaim} items={choices.map(c=>({value:c.id,label:c.domain}))}/>}</Field>:<p className="us-notice">Verify your intended hostname in Identity first.</p>}{data.hosting&&<p>Changing this connection disables the previous hostname and clears its search-engine verification settings.</p>}<div className="us-modal-actions"><Action type="submit" disabled={sample||busy||!claim}>{busy?<Busy/>:"Connect hostname"}</Action></div></form>;
}
function DiscoveryForm({data,busy,sample,onSave}:{data:PresenceState;busy:boolean;sample:boolean;onSave:(p:Record<string,unknown>)=>void}){
  const initial=data.discovery||{google_token:"",bing_token:"",indexnow_enabled:false,revision:0},[v,setV]=useState(initial),[consent,setConsent]=useState(false);
  return <form className="us-form" onSubmit={e=>{e.preventDefault();onSave({...v,...(v.indexnow_enabled?{consent:"indexnow-public-urls-v1"}:{})});}}><p>Copy the content value from each search engine’s HTML verification tag. These values are published only on your connected hostname. Complete verification in the corresponding search console.</p><Field label="Google verification token (optional)">{id=><Input id={id} maxLength={200} pattern="[a-zA-Z0-9_-]*" value={v.google_token} onChange={e=>setV({...v,google_token:e.target.value.trim()})}/>}</Field><Field label="Bing verification token (optional)">{id=><Input id={id} maxLength={200} pattern="[a-zA-Z0-9_-]*" value={v.bing_token} onChange={e=>setV({...v,bing_token:e.target.value.trim()})}/>}</Field><label className="us-check"><input type="checkbox" checked={v.indexnow_enabled} onChange={e=>setV({...v,indexnow_enabled:e.target.checked})}/>Notify search engines when public pages change</label>{v.indexnow_enabled&&<><p>Send canonical public page URLs and a hostname verification key to api.indexnow.org. Participating search engines may share these URLs. This includes page additions, updates, and removals; it excludes private source and test content.</p><label className="us-check"><input type="checkbox" required checked={consent} onChange={e=>setConsent(e.target.checked)}/>I authorize recurring IndexNow notifications for this hostname.</label></>}<div className="us-modal-actions"><Action type="submit" disabled={sample||busy||v.indexnow_enabled&&!consent}>{busy?<Busy/>:"Save discovery settings"}</Action></div></form>;
}
