"use client";

import {useCallback,useEffect,useRef,useState,type FormEvent} from "react";
import {Copy,Download,History,LockKeyhole,LogOut,Mail,Pencil,Plus,ShieldCheck,Users} from "./icons";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Action,Busy,Choice,Empty,ErrorNotice,Field,Modal,Pill,bytes,saveFile,stamp,useApi,type Command} from "./shared";
import {activityLabel,invitationState,invitationToken,type WorkspaceMember,type WorkspaceSettings} from "@/lib/production/workspace";
import type {Activity,RuntimeStatus,SpaceState} from "@/lib/production/types";

type SettingsProps={state:SpaceState;user:{id:string;email:string};status:RuntimeStatus|null;command:Command;signOut:()=>void;canEdit:boolean;sample?:boolean;onLeft?:()=>Promise<void>};
type SettingsSection="general"|"access"|"activity"|"account"|"connections";
const roles=[{value:"viewer",label:"Viewer — read only"},{value:"editor",label:"Editor — add and review knowledge"}];

function EditDetails({state,command,onClose}:{state:SpaceState;command:Command;onClose:()=>void}){
  const [original,setOriginal]=useState(state.space),[name,setName]=useState(state.space.name),[description,setDescription]=useState(state.space.description),[email,setEmail]=useState(state.space.contact_email),[busy,setBusy]=useState(false),[error,setError]=useState("");
  const dirty=name!==original.name||description!==original.description||email!==original.contact_email;
  async function submit(event:FormEvent){event.preventDefault();setBusy(true);setError("");try{await command("update_space",{name,description,contact_email:email,revision:original.content_revision});onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal open onClose={()=>!busy&&onClose()} dirty={dirty} title="Edit presence details" description="These details become public with your next release."><form onSubmit={submit}><fieldset disabled={busy}>
    <Field label="Name">{id=><Input autoFocus id={id} required maxLength={200} value={name} onChange={e=>setName(e.target.value)}/>}</Field>
    <Field label="Description">{id=><Textarea id={id} rows={6} maxLength={5000} value={description} onChange={e=>setDescription(e.target.value)} placeholder="What does this collection cover?"/>}</Field>
    <Field label="Public contact email" hint="Optional. Your account email remains private.">{id=><Input id={id} type="email" maxLength={200} value={email} onChange={e=>setEmail(e.target.value)}/>}</Field>
  </fieldset><ErrorNotice message={error}/>{error&&<button type="button" className="us-link" disabled={busy} onClick={()=>{setOriginal(state.space);setName(state.space.name);setDescription(state.space.description);setEmail(state.space.contact_email);setError("");}}>Discard edits and reload saved details</button>}<div className="us-modal-actions"><small className="us-muted">Saved to your private draft</small><Action type="submit" disabled={busy||!dirty}>{busy?<Busy label="Saving…"/>:"Save details"}</Action></div></form></Modal>;
}

function InviteMember({command,onClose,onSaved,sample}:{command:Command;onClose:()=>void;onSaved:()=>Promise<void>;sample:boolean}){
  const [email,setEmail]=useState(""),[role,setRole]=useState("viewer"),[busy,setBusy]=useState(false),[error,setError]=useState(""),[link,setLink]=useState(""),[copied,setCopied]=useState(false);
  const token=useRef(invitationToken()),request=useRef(crypto.randomUUID()),requestKey=useRef("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{const key=email.trim().toLowerCase()+":"+role;if(requestKey.current!==key){request.current=crypto.randomUUID();token.current=invitationToken();requestKey.current=key;}const result=await command("create_invitation",{email,role,token:token.current,request_id:request.current});const url=new URL(sample?"/demo":"/",location.origin);url.searchParams.set("invite",String(result.id));url.searchParams.set("token",token.current);setLink(url.href);await onSaved();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal open onClose={()=>!busy&&onClose()} dirty={!link&&!!email} title="Invite someone" description="Give someone access to this private workspace.">{link?<>
    <div className="us-success" role="status">{sample?"Sample invitation created.":"Invitation created."} Share the link with {email}.</div>
    <Field label="Invitation link" hint="Copy this link now. It expires in 7 days and can only be accepted by a confirmed account with this email.">{id=><Input id={id} readOnly value={link} onFocus={e=>e.target.select()}/>}</Field>
    <p className="us-small us-muted">You send this link yourself. Unsite has not sent an email.</p><ErrorNotice message={error}/><div className="us-modal-actions"><Action secondary onClick={onClose}>Done</Action><Action onClick={async()=>{try{await navigator.clipboard.writeText(link);setCopied(true);}catch{setError("Select the invitation link and copy it manually.");}}}><Copy size={16}/>{copied?"Copied":"Copy invitation"}</Action></div>
  </>:<form onSubmit={submit}><fieldset disabled={busy}><Field label="Email address">{id=><Input autoFocus id={id} type="email" required maxLength={254} autoComplete="email" value={email} onChange={e=>setEmail(e.target.value)}/>}</Field><Field label="Access level">{()=> <Choice value={role} onChange={setRole} items={roles} label="Invitation access level"/>}</Field><div className="us-notice"><ShieldCheck size={17}/><span>Only the workspace owner can publish releases, invite people, or change access.</span></div></fieldset><ErrorNotice message={error}/><div className="us-modal-actions"><span className="us-small us-muted">Valid for 7 days</span><Action type="submit" disabled={busy}>{busy?<Busy label="Creating…"/>:<><Plus size={16}/>Create invitation</>}</Action></div></form>}</Modal>;
}

function EditMember({member,command,onClose,onSaved}:{member:WorkspaceMember;command:Command;onClose:()=>void;onSaved:()=>Promise<void>}){
  const [role,setRole]=useState(member.role),[remove,setRemove]=useState(false),[busy,setBusy]=useState(false),[error,setError]=useState("");
  async function submit(e:FormEvent){e.preventDefault();setBusy(true);setError("");try{await command(remove?"remove_member":"update_member",{user_id:member.user_id,...(!remove?{role}:{})});await onSaved();onClose();}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal open onClose={()=>!busy&&onClose()} dirty={role!==member.role||remove} title="Manage access" description={member.email}><form onSubmit={submit}><fieldset disabled={busy}><Field label="Access level">{()=> <Choice value={role} onChange={value=>setRole(value as typeof role)} items={roles} label="Member access level" disabled={remove}/>}</Field><section className="us-settings-danger"><h3>Remove from this workspace</h3><p>They lose access to this workspace. Knowledge they contributed stays intact.</p><label className="us-check"><input type="checkbox" checked={remove} onChange={e=>setRemove(e.target.checked)}/>Remove this person’s access</label></section></fieldset><ErrorNotice message={error}/><div className="us-modal-actions"><span/><Action type="submit" disabled={busy||role===member.role&&!remove}>{busy?<Busy label="Saving…"/>:remove?"Remove access":"Save access"}</Action></div></form></Modal>;
}

function PasswordPanel({onClose,sample}:{onClose:()=>void;sample:boolean}){
  const api=useApi();
  const [current,setCurrent]=useState(""),[password,setPassword]=useState(""),[confirm,setConfirm]=useState(""),[busy,setBusy]=useState(false),[error,setError]=useState(""),[done,setDone]=useState(false);
  async function submit(e:FormEvent){e.preventDefault();if(password!==confirm){setError("The new passwords don’t match.");return;}setBusy(true);setError("");try{await api("/api/auth",{action:"change_password",current_password:current,password});setCurrent("");setPassword("");setConfirm("");setDone(true);}catch(e){setError((e as Error).message);}finally{setBusy(false);}}
  return <Modal open onClose={()=>!busy&&onClose()} dirty={!done&&!!(current||password||confirm)} title="Change password" description="Use a unique password with at least 12 characters.">{sample?<div className="us-notice">Passwords belong to real accounts. Sign in to your workspace to change yours.</div>:done?<><p className="us-success" role="status">Your password has been updated.</p><Action onClick={onClose}>Done</Action></>:<form onSubmit={submit}><fieldset disabled={busy}><Field label="Current password">{id=><Input id={id} autoFocus type="password" autoComplete="current-password" required maxLength={128} value={current} onChange={e=>setCurrent(e.target.value)}/>}</Field><Field label="New password">{id=><Input id={id} type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={password} onChange={e=>setPassword(e.target.value)}/>}</Field><Field label="Confirm new password">{id=><Input id={id} type="password" autoComplete="new-password" required minLength={12} maxLength={128} value={confirm} onChange={e=>setConfirm(e.target.value)}/>}</Field></fieldset><ErrorNotice message={error}/><div className="us-modal-actions"><span/><Action type="submit" disabled={busy}>{busy?<Busy label="Updating…"/>:"Update password"}</Action></div></form>}</Modal>;
}

function ActivityLog({spaceId,revision}:{spaceId:string;revision:string}){
  const api=useApi();const [items,setItems]=useState<Activity[]>([]),[count,setCount]=useState(0),[page,setPage]=useState(0),[busy,setBusy]=useState(true),[error,setError]=useState(""),[retry,setRetry]=useState(0);
  useEffect(()=>{let alive=true;setBusy(true);setError("");api<{items:Activity[];count:number}>(`/api/app/activity?space=${spaceId}&offset=${page*50}`).then(d=>{if(alive){setItems(d.items);setCount(d.count);}}).catch(e=>alive&&setError(e.message)).finally(()=>alive&&setBusy(false));return()=>{alive=false;};},[api,spaceId,page,revision,retry]);
  return <section className="us-card"><div className="us-between"><div><h3>Workspace activity</h3><p className="us-muted">A shared history of changes in this workspace.</p></div><History size={22}/></div><ErrorNotice message={error}/>{error?<Action secondary onClick={()=>setRetry(v=>v+1)}>Try again</Action>:busy?<Busy label="Loading activity…"/>:!items.length?<Empty icon={<History size={26}/>} title="No activity yet" description="Workspace changes will appear here."/>:<><ol className="us-settings-activity">{items.map(event=><li key={event.id}><span className="us-activity-dot"/><div><strong>{activityLabel(event)}</strong><small>{stamp(event.created_at)}</small></div></li>)}</ol><div className="us-pagination"><Action secondary disabled={page===0} onClick={()=>setPage(p=>p-1)}>Previous</Action><span>{page*50+1}–{Math.min((page+1)*50,count)} of {count}</span><Action secondary disabled={(page+1)*50>=count} onClick={()=>setPage(p=>p+1)}>Next</Action></div></>}</section>;
}

export function Settings({state,user,status,command,signOut,canEdit,sample=false,onLeft}:SettingsProps){
  const api=useApi();
  const [section,setSection]=useState<SettingsSection>("general"),[settings,setSettings]=useState<WorkspaceSettings|null>(null),[error,setError]=useState(""),[message,setMessage]=useState(""),[busy,setBusy]=useState(""),[panel,setPanel]=useState<"details"|"invite"|"password"|"leave"|null>(null),[member,setMember]=useState<WorkspaceMember|null>(null),[confirmed,setConfirmed]=useState(false);
  const owner=state.memberships.find(m=>m.user_id===user.id)?.role==="owner";
  const request=useRef(0);
  const load=useCallback(async()=>{const seq=++request.current;try{const data=await api<WorkspaceSettings>("/api/app/workspace-settings?space="+state.space.id);if(seq===request.current){setSettings(data);setError("");}}catch(e){if(seq===request.current)setError((e as Error).message);}},[api,state.space.id]);
  useEffect(()=>{void load();return()=>{request.current++;};},[load,state.space.content_revision,state.activity[0]?.id]);
  async function perform(key:string,task:()=>Promise<void>){setBusy(key);setError("");setMessage("");try{await task();}catch(e){setError((e as Error).message);}finally{setBusy("");}}
  const usage=settings?.usage;
  const publicAddress=status?.publicBase?status.publicBase+"/"+state.space.id:"";
  return <><div className="us-section-heading"><div><span className="us-eyebrow">Your workspace</span><h1>Settings</h1><p>Manage the details, people, and connections behind your knowledge.</p></div><Pill>{owner?"Owner":canEdit?"Editor":"Viewer"}</Pill></div>
    <nav className="us-section-tabs" aria-label="Settings sections">{([['general','General'],['access','People & access'],['activity','Activity'],['account','Your account'],['connections','Connections']] as const).map(([key,label])=><button key={key} type="button" aria-current={section===key?"page":undefined} onClick={()=>{setSection(key);setMessage("");}}>{label}</button>)}</nav>
    <ErrorNotice message={error}/>{error&&<button type="button" className="us-link" onClick={()=>void load()}>Refresh settings</button>}{message&&<div className="us-success" role="status">{message}</div>}
    {section==="general"&&<div className="us-settings-grid"><div><section className="us-card"><div className="us-between"><h3>Presence details</h3>{canEdit&&<Action secondary onClick={()=>setPanel("details")}><Pencil size={15}/>Edit details</Action>}</div><dl className="us-detail-list"><div><dt>Name</dt><dd>{state.space.name}</dd></div><div><dt>Description</dt><dd>{state.space.description||<span className="us-muted">Add a short introduction to this collection.</span>}</dd></div><div><dt>Public contact</dt><dd>{state.space.contact_email||<span className="us-muted">No public contact email</span>}</dd></div></dl><p className="us-small us-muted">Changes appear publicly after you publish a new release.</p></section><section className="us-card"><h3>Your data, within reach</h3><p className="us-muted">Download your knowledge, source text, relationships, review history, and releases in one JSON export. Original uploaded files can be downloaded from Sources.</p>{owner?<Action secondary disabled={!!busy} onClick={()=>void perform("export",async()=>{const data=await api("/api/app/workspace-export?space="+state.space.id);saveFile("unsite-workspace-"+new Date().toISOString().slice(0,10)+".json",data);setMessage("Workspace export downloaded.");})}>{busy==="export"?<Busy label="Preparing export…"/>:<><Download size={16}/>Export workspace</>}</Action>:<p className="us-small us-muted">The owner can export this workspace.</p>}</section></div><section className="us-card us-settings-summary"><h3>Workspace at a glance</h3>{usage?<dl className="us-detail-list">{[["Active sources",usage.sources],["Archived sources",usage.archived_sources],["Source versions",usage.versions],["Stored files",bytes(usage.stored_bytes)],["Knowledge entries",usage.records],["Included in draft",usage.included_records],["Awaiting review",usage.pending_reviews],["Releases",usage.releases]].map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl>:error?<p className="us-muted">Refresh to load workspace totals.</p>:<Busy label="Loading totals…"/>}<p className="us-small us-muted">Created {stamp(state.space.created_at)}</p></section></div>}
    {section==="access"&&<><section className="us-card"><div className="us-between"><div><h3>People with access</h3><p className="us-muted">Editors manage knowledge. Viewers can browse. Only the owner can publish and manage access.</p></div>{owner&&<Action onClick={()=>setPanel("invite")}><Plus size={16}/>Invite someone</Action>}</div>{settings?<div className="us-member-list">{settings.members.map(person=><div className="us-member-row" key={person.user_id}><span className="us-avatar"><Users size={16}/></span><div><strong>{person.email}{person.user_id===user.id&&" (you)"}</strong><small>Joined {stamp(person.created_at)}</small></div><Pill>{person.role}</Pill>{owner&&person.role!=="owner"&&<Action secondary onClick={()=>setMember(person)}>Manage</Action>}</div>)}</div>:!error&&<Busy label="Loading people…"/>}</section>{owner&&<section className="us-card"><h3>Invitations</h3><p className="us-muted">Share invitation links directly. Each link is tied to the recipient’s confirmed email.</p>{settings?.invitations.length?<div className="us-member-list">{settings.invitations.map(invitation=><div className="us-member-row" key={invitation.id}><span className="us-avatar"><Mail size={16}/></span><div><strong>{invitation.email}</strong><small>{invitation.role} · {invitationState(invitation)==="Pending"?"Expires "+stamp(invitation.expires_at):"Created "+stamp(invitation.created_at)}</small></div><Pill>{invitationState(invitation)}</Pill>{invitationState(invitation)==="Pending"&&<Action secondary disabled={!!busy} onClick={()=>void perform(invitation.id,async()=>{await command("revoke_invitation",{invitation_id:invitation.id});await load();})}>{busy===invitation.id?<Busy label="Revoking…"/>:"Revoke"}</Action>}</div>)}</div>:<Empty icon={<Mail size={27}/>} title="No invitations yet" description="Invite a collaborator to help shape your knowledge."/>}</section>}{!owner&&onLeft&&<section className="us-card"><h3>Leave this workspace</h3><p className="us-muted">You will lose access. Your contributions remain with the workspace.</p><Action secondary onClick={()=>{setConfirmed(false);setPanel("leave");}}>Leave workspace</Action></section>}</>}
    {section==="activity"&&<ActivityLog spaceId={state.space.id} revision={state.activity[0]?.id||""}/>}
    {section==="account"&&<div className="us-settings-grid"><section className="us-card"><h3>Your account</h3><dl className="us-detail-list"><div><dt>Email address</dt><dd>{user.email}</dd></div></dl><p className="us-muted">This address is private unless you add it to your public presence.</p><Action secondary onClick={()=>setPanel("password")}><LockKeyhole size={16}/>Change password</Action></section><section className="us-card"><h3>Sessions</h3><p className="us-muted">Manage where you’re signed in.</p><div className="us-settings-actions"><Action secondary disabled={!!busy} onClick={()=>void perform("sessions",async()=>{if(sample){setMessage("Session controls are available in your signed-in workspace.");return;}await api("/api/auth",{action:"signout_others"});setMessage("Other sessions signed out. Previously issued access tokens remain valid until they expire.");})}>{busy==="sessions"?<Busy/>:"Sign out other sessions"}</Action><Action secondary onClick={signOut}><LogOut size={16}/>{sample?"Reset demo":"Sign out of this session"}</Action></div></section></div>}
    {section==="connections"&&<div className="us-settings-grid"><section className="us-card us-service-state"><h3>Connected services</h3><p className="us-muted">The services behind importing and preparing your material.</p>{[{label:"Private source storage",ready:status?.storage},{label:"Background source reading",ready:status?.processing},{label:"AI preparation",ready:status?.model}].map(item=><div className="us-between" key={item.label}><span>{item.label}</span><Pill>{sample?"Demo":!status?"Unavailable":item.ready?"Connected":"Not connected"}</Pill></div>)}<p className="us-small us-muted">AI preparation asks for your approval before using a source. You can add and publish knowledge manually at any time.</p></section><section className="us-card"><h3>Publication address</h3><p className="us-muted">Your hosted address stays the same across releases. It serves only the release you choose to publish.</p>{publicAddress?<><Field label="Hosted address">{id=><Input id={id} readOnly value={publicAddress} onFocus={e=>e.target.select()}/>}</Field><Action secondary onClick={()=>void perform("copy",async()=>{try{await navigator.clipboard.writeText(publicAddress);setMessage("Publication address copied.");}catch{throw new Error("Select the address and copy it manually.");}})}><Copy size={16}/>Copy address</Action></>:<p className="us-small us-muted">{sample?"Sample publications stay in this demo. Your real workspace has a persistent hosted address.":"Refresh the workspace to check the publication service."}</p>}</section></div>}
    {panel==="details"&&<EditDetails state={state} command={command} onClose={()=>setPanel(null)}/>}
    {panel==="invite"&&<InviteMember command={command} onSaved={load} sample={sample} onClose={()=>setPanel(null)}/>}
    {member&&<EditMember member={member} command={command} onSaved={load} onClose={()=>setMember(null)}/>}
    {panel==="password"&&<PasswordPanel sample={sample} onClose={()=>setPanel(null)}/>}
    {panel==="leave"&&<Modal open readOnly onClose={()=>!busy&&setPanel(null)} title="Leave workspace" description={state.space.name}><p>You’ll need a new invitation to return. Your knowledge contributions will stay here.</p><label className="us-check"><input type="checkbox" checked={confirmed} onChange={e=>setConfirmed(e.target.checked)}/>I understand that I’ll lose access.</label><ErrorNotice message={error}/><div className="us-modal-actions"><Action secondary disabled={!!busy} onClick={()=>setPanel(null)}>Keep access</Action><Action disabled={!confirmed||!!busy} onClick={()=>void perform("leave",async()=>{await api("/api/app/leave_workspace",{space_id:state.space.id});await onLeft?.();})}>{busy?<Busy label="Leaving…"/>:"Leave workspace"}</Action></div></Modal>}
  </>;
}
