"use client";
import {useCallback,useEffect,useRef,useState,type FormEvent} from "react";
import {Input} from "@/components/ui/input";
import {Textarea} from "@/components/ui/textarea";
import {Globe,Plus,ShieldCheck,RefreshCw,FileText,FlaskConical} from "./icons";
import {Action,Busy,Choice,Empty,ErrorNotice,External,Field,Modal,Pill,stamp,useApi,saveFile,type Command} from "./shared";
import {claimState,emptyPublisher,entityTypes,ownershipRecord,visibilitySummary,type PresenceState,type Publisher,type PublicResource,type VisibilityObservation} from "@/lib/production/presence";
import type {RuntimeStatus,SpaceState} from "@/lib/production/types";

type Props={state:SpaceState;status:RuntimeStatus|null;command:Command;isOwner:boolean;canEdit:boolean;sample?:boolean};
type Section="identity"|"resources"|"monitoring"|"observations";
type Panel={kind:"publisher"}|{kind:"domain"}|{kind:"resource";resource?:PublicResource}|{kind:"observation";observation?:VisibilityObservation};
const lines=(value:string)=>value.split(/\r?\n/).map(v=>v.trim()).filter(Boolean);
const showDate=(value:string|null)=>value?stamp(value):"Not checked yet";

export function Visibility({state,status,command,isOwner,canEdit,sample=false}:Props){
  const api=useApi(),sequence=useRef(0),[data,setData]=useState<PresenceState|null>(null),[section,setSection]=useState<Section>("identity"),[panel,setPanel]=useState<Panel|null>(null),[busy,setBusy]=useState(""),[error,setError]=useState("");
  const load=useCallback(async()=>{const request=++sequence.current;try{const value=await api<PresenceState>("/api/app/presence?space="+state.space.id);if(request===sequence.current){setData(value);setError("");}}catch(e){if(request===sequence.current)setError((e as Error).message);}},[api,state.space.id]);
  useEffect(()=>{void load();const timer=setInterval(()=>{if(document.visibilityState==="visible")void load();},15000);return()=>{sequence.current++;clearInterval(timer);};},[load]);
  async function run(action:string,payload:Record<string,unknown>){setBusy(action);setError("");try{await command(action,payload);await load();return true;}catch(e){setError((e as Error).message);return false;}finally{setBusy("");}}
  async function save(action:string,payload:Record<string,unknown>){if(await run(action,payload))setPanel(null);}
  const publicUrl=(status?.publicOrigin||"https://unsite.vercel.app")+"/p/"+state.space.id,apiUrl=status?.publicBase?status.publicBase+"/"+state.space.id:"";
  const totals=data?visibilitySummary(data.observations,[publicUrl,...(apiUrl?[apiUrl]:[])]):null;
  const officialHost=(()=>{try{return new URL(data?.publisher.official_url||"").hostname;}catch{return "";}})();
  const proof=data?.claims.find(c=>c.domain===officialHost&&claimState(c)==="verified");
  return <>
    <div className="us-page-heading"><div><span className="us-eyebrow">Be found. Be understood.</span><h1>Visibility</h1><p>Establish your identity, keep sources current, and measure where your knowledge appears.</p></div></div>
    {sample&&<div className="us-notice">Sample workspace. Domain checks, monitoring, and observations stay local; they do not contact external services.</div>}
    <div className="us-geo-readiness us-card"><div><ShieldCheck size={20}/><span>Official domain<strong>{proof?"Verified":"Verification needed"}</strong></span></div><div><Globe size={20}/><span>Publication<strong>{state.space.active_release_id?"Public release available":"Not published"}</strong></span></div><div><RefreshCw size={20}/><span>Source monitoring<strong>{data?.monitors.filter(m=>m.cadence!=="off").length||0} scheduled</strong></span></div><div><FlaskConical size={20}/><span>Web observations<strong>{totals?.observations||0} recorded</strong></span></div></div>
    <div className="us-geo-tabs" role="tablist" aria-label="Visibility sections" onKeyDown={e=>{if(!["ArrowLeft","ArrowRight","Home","End"].includes(e.key))return;e.preventDefault();const tabs=[...e.currentTarget.querySelectorAll<HTMLButtonElement>('button[role="tab"]')],current=tabs.indexOf(document.activeElement as HTMLButtonElement),next=e.key==="Home"?0:e.key==="End"?tabs.length-1:(current+(e.key==="ArrowRight"?1:-1)+tabs.length)%tabs.length;tabs[next]?.click();tabs[next]?.focus();}}>{([{id:"identity",label:"Identity"},{id:"resources",label:"Resources"},{id:"monitoring",label:"Source updates"},{id:"observations",label:"Observations"}] as const).map(t=><button type="button" role="tab" tabIndex={section===t.id?0:-1} aria-selected={section===t.id} aria-controls={"geo-"+t.id} id={"geo-tab-"+t.id} key={t.id} onClick={()=>setSection(t.id)}>{t.label}</button>)}</div>
    <ErrorNotice message={error}/>
    {!data?<div className="us-card us-geo-card">{error?<Action secondary onClick={()=>void load()}>Try again</Action>:<Busy label="Loading visibility…"/>}</div>:<section id={"geo-"+section} role="tabpanel" aria-labelledby={"geo-tab-"+section}>
      {section==="identity"&&<>
        <div className="us-subheading"><h2>Publisher identity</h2>{isOwner&&<Action secondary onClick={()=>setPanel({kind:"publisher"})}>Edit identity</Action>}</div>
        <div className="us-card us-geo-card"><div className="us-between"><h3>{state.space.name}</h3><Pill>{data.publisher.entity_type}</Pill></div><p className="us-muted">{data.publisher.official_url||"Add your official website to connect this publication to its publisher."}</p>{data.publisher.aliases.length>0&&<p>Also known as {data.publisher.aliases.join(", ")}</p>}<div className="us-geo-links">{data.publisher.profile_urls.map(url=><External key={url} href={url}>{new URL(url).hostname}</External>)}</div><p className="us-small us-muted">Identity changes and resource links are included in your next reviewed release.</p></div>
        <div className="us-subheading"><h2>Domain verification</h2>{isOwner&&<Action secondary onClick={()=>setPanel({kind:"domain"})}><Plus size={16}/>Add domain</Action>}</div>
        <p className="us-small us-muted">Prove control of your official website by adding a DNS record. Proof is checked daily and expires if it cannot be renewed. This does not host your Unsite on that domain.</p>
        {data.claims.length?<div className="us-card us-geo-list">{data.claims.map(c=>{const proof=ownershipRecord(state.space.id,c),status=claimState(c);return <article key={c.id}><div className="us-between"><h3>{c.domain}</h3><Pill tone={status==="verified"?"green":"neutral"}>{status}</Pill></div><p className="us-small us-muted">{showDate(c.checked_at)}{c.expires_at?" · Expires "+stamp(c.expires_at):""}</p>{status!=="revoked"&&<dl className="us-geo-dns"><div><dt>Type</dt><dd>TXT</dd></div><div><dt>Name</dt><dd><code>{proof.name}</code></dd></div><div><dt>Value</dt><dd><code>{proof.value}</code></dd></div></dl>}{c.error_message&&<p className="us-small">{c.error_message}</p>}{isOwner&&<div className="us-inline-actions">{status==="revoked"?<Action secondary disabled={!!busy} onClick={()=>void run("claim_domain",{domain:c.domain,request_id:crypto.randomUUID()})}>Create new proof</Action>:<><Action secondary disabled={!!busy} onClick={()=>void run("check_domain",{claim_id:c.id})}>Check proof</Action><button disabled={!!busy} onClick={()=>void run("revoke_domain",{claim_id:c.id})}>Revoke proof</button></>}</div>}</article>;})}</div>:<Empty icon={<Globe size={26}/>} title="Connect your official identity" description="Use a domain you control. Verification confirms the publisher controls that domain; evidence and owner approval support the content separately."/>}
        {state.space.active_release_id&&!sample&&<div className="us-card us-geo-card"><h3>Connect your website</h3><p>Link to your Unsite from your official website’s About or Resources page. Keep the name and profile links consistent.</p><code className="us-geo-code">{publicUrl}</code><External href={publicUrl}>Open public page</External></div>}
        <div className="us-subheading"><h2>Public delivery</h2>{canEdit&&<Action secondary disabled={sample||!!busy||!state.space.active_release_id||(data.delivery_checks||[]).some(c=>["queued","running"].includes(c.status))} onClick={()=>void run("check_delivery",{request_id:crypto.randomUUID()})}>Check API and MCP</Action>}</div>
        <p className="us-small us-muted">Checks public endpoints and a complete record through HTTP and MCP. These checks make no AI requests and do not measure search visibility.</p>
        {data.delivery_checks?.length?<div className="us-card us-geo-list">{data.delivery_checks.slice(0,5).map(c=><article key={c.id}><div className="us-between"><strong>{stamp(c.created_at)}</strong><Pill tone={c.result?.passed?"green":c.status==="failed"||c.result?.passed===false?"amber":"neutral"}>{c.status==="completed"?c.result?.passed?"API checks passed":"Needs attention":c.status}</Pill></div>{c.release_id!==state.space.active_release_id&&<p className="us-small us-muted">This check belongs to a previous release.</p>}{c.result?.checks.map(check=><p className="us-small" key={check.name}>{check.passed?"✓":"—"} {check.name}: {check.detail}</p>)}{c.index_results?.map((test,i)=><p className="us-small" key={"case-"+i}>{test.passed?"✓":"—"} Private index test: {test.question} · {test.passed?"Passed":"Needs attention"}</p>)}{c.error_message&&<p>{c.error_message}</p>}{c.result&&<Action secondary onClick={()=>saveFile("unsite-delivery-check.json",{...c.result,index_results:c.index_results||[]})}>Export result</Action>}</article>)}</div>:<p className="us-small us-muted">{sample?"Public delivery checks are unavailable in the sample.":"Publish a release, then check its public endpoints."}</p>}
      </>}
      {section==="resources"&&<>
        <div className="us-subheading"><h2>Approved resources</h2>{isOwner&&<Action onClick={()=>setPanel({kind:"resource"})}><Plus size={16}/>Add resource</Action>}</div>
        <p className="us-small us-muted">Link public documentation, datasets, media kits, and service descriptions. Resources become public with your next release. Private source uploads remain private.</p>
        {data.resources.length?<div className="us-card us-geo-list">{data.resources.map(r=><article key={r.id}><div className="us-between"><div><h3>{r.title}</h3><p className="us-small us-muted">{r.mime_type}{r.version_label?" · "+r.version_label:""}{r.as_of?" · As of "+r.as_of:""}</p></div><Pill>{r.active?"Included":"Excluded"}</Pill></div><p>{r.description}</p><div className="us-inline-actions"><External href={r.url}>Open resource</External>{isOwner&&<button onClick={()=>setPanel({kind:"resource",resource:r})}>Edit resource</button>}</div></article>)}</div>:<Empty icon={<FileText size={26}/>} title="Give agents useful resources" description="Add public links with a clear description, format, and version so agents can decide what to read or use."/>}
      </>}
      {section==="monitoring"&&<>
        <div className="us-subheading"><h2>Source updates</h2><Pill>No AI calls</Pill></div><p className="us-small us-muted">Scheduled checks compare page text with the latest version. Changes create a private source version and identify affected entries. Preparing suggestions still requires approval, and publishing remains a separate review.</p>
        {state.sources.some(s=>s.kind==="url"&&!s.archived_at)?<div className="us-card us-geo-list">{state.sources.filter(s=>s.kind==="url"&&!s.archived_at).map(s=>{const m=data.monitors.find(m=>m.source_id===s.id);return <article key={s.id}><h3>{s.title}</h3><p className="us-small us-muted us-geo-wrap">{s.origin_url}</p><div className="us-geo-monitor-actions"><Choice label={"Check frequency for "+s.title} value={m?.cadence||"off"} disabled={!canEdit||!!busy} onChange={cadence=>void run("save_monitor",{source_id:s.id,cadence})} items={[{value:"off",label:"Off"},{value:"daily",label:"Daily"},{value:"weekly",label:"Weekly"}]}/>{canEdit&&<Action secondary disabled={!!busy} onClick={()=>void run("check_source",{source_id:s.id})}>Check now</Action>}</div><p className="us-small us-muted">{showDate(m?.last_checked_at||null)}{m?.next_check_at?" · Next "+stamp(m.next_check_at):""}</p>{m?.error_message&&<p className="us-small">{m.error_message}</p>}</article>;})}</div>:<Empty icon={<RefreshCw size={26}/>} title="Monitor your web sources" description="Add a web page in Sources to schedule daily or weekly checks. Documents and notes can be updated by adding a new version."/>}
        <div className="us-subheading"><h2>Detected changes</h2><span className="us-small us-muted">Latest 100</span></div>{data.changes.length?<div className="us-card us-geo-list">{data.changes.map(c=><article key={c.id}><div className="us-between"><h3>{state.sources.find(s=>s.id===c.source_id)?.title||"Updated source"}</h3><Pill>{c.affected_record_ids.length} affected entries</Pill></div><p className="us-small us-muted">{stamp(c.created_at)}</p><p>Review the new version in Sources, then prepare and approve any knowledge changes.</p>{c.affected_record_ids.length>0&&<p className="us-small">{c.affected_record_ids.map(id=>state.records.find(r=>r.id===id)?.title||id).join(", ")}</p>}</article>)}</div>:<p className="us-small us-muted">No source changes have been detected.</p>}
      </>}
      {section==="observations"&&<>
        <div className="us-subheading"><h2>Recorded observations</h2>{canEdit&&<div className="us-inline-actions"><Action secondary disabled={!data.observations.length} onClick={()=>saveFile("unsite-visibility-observations.json",{exported_at:new Date().toISOString(),scope:"Latest 500 recorded observations",observations:data.observations})}>Export observations</Action><Action onClick={()=>setPanel({kind:"observation"})}><Plus size={16}/>Record observation</Action></div>}</div><p className="us-small us-muted">Record real questions and responses from ChatGPT or another agent. Web discovery is measured separately from tests that explicitly connect to your API or MCP server. These are your recorded observations, not an automated ranking report.</p>
        {!!totals?.observations&&<div className="us-geo-readiness us-card"><div><span>Web discovery<strong>{totals.cited} / {totals.observations} cite this Unsite</strong></span></div><div><span>Preferred source<strong>{totals.preferred} / {totals.preference_reviewed} assessed</strong></span></div><div><span>Answer accuracy<strong>{totals.correct} / {totals.accuracy_reviewed} reviewed</strong></span></div><div><span>Outdated answers<strong>{totals.stale} / {totals.staleness_reviewed} assessed</strong></span></div></div>}
        {data.observations.length?<div className="us-card us-geo-list">{data.observations.map(o=><article key={o.id}><div className="us-between"><h3>{o.question}</h3><Pill>{o.mode==="web"?"Web discovery":o.mode.toUpperCase()+" connection"}</Pill></div><p className="us-small us-muted">{o.platform} · {stamp(o.observed_at)}</p><p className="us-small">Preferred source: {o.preferred_source===null?"Not assessed":o.preferred_source?"Yes":"No"} · Accurate: {o.correct===null?"Not assessed":o.correct?"Yes":"No"} · Outdated: {o.stale_answer==null?"Not assessed":o.stale_answer?"Yes":"No"}</p><div className="us-geo-links">{o.cited_urls.map((url,i)=><External key={url+i} href={url}>Citation {i+1}</External>)}</div>{o.notes&&<p className="us-geo-wrap">{o.notes}</p>}<div className="us-inline-actions">{o.evidence_url&&<External href={o.evidence_url}>Response evidence</External>}{canEdit&&<button onClick={()=>setPanel({kind:"observation",observation:o})}>View details</button>}</div></article>)}</div>:<Empty icon={<FlaskConical size={26}/>} title="Start with real questions" description="Ask about your company, person, or subject in an AI search product. Record whether it discovers and cites your Unsite, and whether the answer is accurate."/>}
      </>}
    </section>}
    {panel&&data&&<Modal open readOnly={panel.kind==="observation"&&!!panel.observation} onClose={()=>!busy&&setPanel(null)} title={panel.kind==="publisher"?"Publisher identity":panel.kind==="domain"?"Verify a domain":panel.kind==="resource"?panel.resource?"Edit resource":"Add resource":panel.observation?"Observation details":"Record an observation"} description={panel.kind==="domain"?"Add a domain you control. Unsite will give you a TXT record to put in its DNS settings.":panel.kind==="observation"?"Save what actually happened, including the question and cited URLs.":"These changes stay in your draft until you review and publish a release."}>
      {panel.kind==="publisher"&&<PublisherForm value={data.publisher} busy={!!busy} onSave={p=>void save("save_publisher",p)}/>}
      {panel.kind==="domain"&&<DomainForm busy={!!busy} onSave={domain=>void save("claim_domain",{domain,request_id:crypto.randomUUID()})}/>}
      {panel.kind==="resource"&&<ResourceForm resource={panel.resource} busy={!!busy} onSave={p=>void save("save_resource",p)}/>}
      {panel.kind==="observation"&&<ObservationForm observation={panel.observation} busy={!!busy} onSave={p=>void save("save_observation",p)} onDelete={id=>void save("delete_observation",{observation_id:id})}/>}
      <ErrorNotice message={error}/>
    </Modal>}
  </>;
}

function PublisherForm({value,busy,onSave}:{value:Publisher;busy:boolean;onSave:(p:Record<string,unknown>)=>void}){
  const [v,setV]=useState(value),[aliases,setAliases]=useState(value.aliases.join("\n")),[urls,setUrls]=useState(value.profile_urls.join("\n"));
  return <form className="us-form" onSubmit={e=>{e.preventDefault();onSave({...v,aliases:lines(aliases),profile_urls:lines(urls)});}}><Field label="Entity type">{()=> <Choice label="Entity type" value={v.entity_type} onChange={s=>setV({...v,entity_type:s as Publisher["entity_type"]})} items={entityTypes.map(t=>({value:t,label:t==="CreativeWork"?"Creative work":t}))}/>}</Field><Field label="Official website" hint="Use the canonical HTTPS address of your official website.">{id=><Input id={id} type="url" value={v.official_url} maxLength={2000} placeholder="https://example.com/" onChange={e=>setV({...v,official_url:e.target.value})}/>}</Field><Field label="Alternate names" hint="One name per line, up to 20. Use established names and aliases.">{id=><Textarea id={id} value={aliases} onChange={e=>setAliases(e.target.value)} rows={3}/>}</Field><Field label="Official profiles" hint="One public HTTPS profile URL per line, up to 12.">{id=><Textarea id={id} value={urls} onChange={e=>setUrls(e.target.value)} rows={4}/>}</Field><div className="us-modal-actions"><Action type="submit" disabled={busy}>{busy?<Busy/>:"Save identity"}</Action></div></form>;
}
function DomainForm({busy,onSave}:{busy:boolean;onSave:(domain:string)=>void}){
  const [domain,setDomain]=useState("");return <form className="us-form" onSubmit={e=>{e.preventDefault();onSave(domain);}}><Field label="Domain" hint="Use the hostname of your official website, including www if it uses www.">{id=><Input id={id} required maxLength={253} placeholder="example.com" value={domain} onChange={e=>setDomain(e.target.value)}/>}</Field><div className="us-modal-actions"><Action type="submit" disabled={busy}>{busy?<Busy/>:"Create DNS proof"}</Action></div></form>;
}
function ResourceForm({resource,busy,onSave}:{resource?:PublicResource;busy:boolean;onSave:(p:Record<string,unknown>)=>void}){
  const [v,setV]=useState<PublicResource>(()=>resource||{id:crypto.randomUUID(),title:"",description:"",url:"",mime_type:"text/html",version_label:"",as_of:null,active:true,revision:0});
  const field=(key:"title"|"description"|"url"|"mime_type"|"version_label",label:string,max:number,type="text")=><Field label={label}>{id=><Input id={id} type={type} required={["title","url","mime_type"].includes(key)} value={v[key]} maxLength={max} onChange={e=>setV({...v,[key]:e.target.value})}/>}</Field>;
  return <form className="us-form" onSubmit={e=>{e.preventDefault();onSave({...v});}}>{field("title","Title",200)}<Field label="Description" hint="Explain what an agent can find or do with this resource.">{id=><Textarea id={id} value={v.description} maxLength={2000} rows={4} onChange={e=>setV({...v,description:e.target.value})}/>}</Field>{field("url","Public HTTPS URL",2000,"url")}{field("mime_type","Content type",100)}{field("version_label","Version (optional)",100)}<Field label="As-of date (optional)">{id=><Input id={id} type="date" value={v.as_of||""} onChange={e=>setV({...v,as_of:e.target.value||null})}/>}</Field><label className="us-check"><input type="checkbox" checked={v.active} onChange={e=>setV({...v,active:e.target.checked})}/>Include in the next release</label><p className="us-small us-muted">The linked file can change outside Unsite. Use a versioned URL when a fixed copy is needed.</p><div className="us-modal-actions"><Action type="submit" disabled={busy}>{busy?<Busy/>:"Save resource"}</Action></div></form>;
}
function ObservationForm({observation,busy,onSave,onDelete}:{observation?:VisibilityObservation;busy:boolean;onSave:(p:Record<string,unknown>)=>void;onDelete:(id:string)=>void}){
  const [v,setV]=useState(()=>observation||{id:crypto.randomUUID(),question:"",platform:"ChatGPT",mode:"web" as const,observed_at:new Date().toISOString(),cited_urls:[] as string[],preferred_source:null as boolean|null,correct:null as boolean|null,stale_answer:null as boolean|null,notes:"",evidence_url:""}),[citations,setCitations]=useState(v.cited_urls.join("\n")),[removing,setRemoving]=useState(false);
  const assessment=(key:"preferred_source"|"correct"|"stale_answer",label:string)=><Field label={label}>{()=> <Choice label={label} disabled={!!observation} value={v[key]==null?"unknown":String(v[key])} onChange={s=>setV({...v,[key]:s==="unknown"?null:s==="true"})} items={[{value:"unknown",label:"Not assessed"},{value:"true",label:"Yes"},{value:"false",label:"No"}]}/>}</Field>;
  function submit(e:FormEvent){e.preventDefault();onSave({...v,cited_urls:lines(citations),request_id:v.id});}
  return <form className="us-form" onSubmit={submit}><Field label="Question">{id=><Textarea id={id} required minLength={2} maxLength={1000} value={v.question} readOnly={!!observation} onChange={e=>setV({...v,question:e.target.value})} rows={3}/>}</Field><Field label="Platform and model">{id=><Input id={id} required maxLength={100} value={v.platform} readOnly={!!observation} onChange={e=>setV({...v,platform:e.target.value})}/>}</Field><Field label="How the agent found the publication">{()=> <Choice label="Discovery mode" disabled={!!observation} value={v.mode} onChange={s=>setV({...v,mode:s as VisibilityObservation["mode"]})} items={[{value:"web",label:"Independent web discovery"},{value:"http",label:"Given an API or page URL"},{value:"mcp",label:"Connected to MCP"}]}/>}</Field><Field label="Observed at (UTC)">{id=><Input id={id} type="datetime-local" required readOnly={!!observation} value={v.observed_at.slice(0,16)} onChange={e=>setV({...v,observed_at:e.target.value?new Date(e.target.value+"Z").toISOString():""})}/>}</Field><Field label="Cited URLs" hint="One URL per line. Include all cited sources; only URLs belonging to this Unsite count toward its citation total.">{id=><Textarea id={id} readOnly={!!observation} value={citations} onChange={e=>setCitations(e.target.value)} rows={4}/>}</Field>{assessment("preferred_source","Was this Unsite the preferred source?")}{assessment("correct","Was the answer accurate?")}{assessment("stale_answer","Did the answer use outdated information?")}<Field label="Response evidence URL (optional)">{id=><Input id={id} type="url" maxLength={2000} value={v.evidence_url} readOnly={!!observation} onChange={e=>setV({...v,evidence_url:e.target.value})}/>}</Field><Field label="Notes and answer excerpt">{id=><Textarea id={id} maxLength={4000} rows={4} value={v.notes} readOnly={!!observation} onChange={e=>setV({...v,notes:e.target.value})}/>}</Field><div className="us-modal-actions">{observation?removing?<><span>Delete this recorded observation?</span><Action secondary onClick={()=>setRemoving(false)}>Keep</Action><Action disabled={busy} onClick={()=>onDelete(observation.id)}>Delete</Action></>:<Action secondary onClick={()=>setRemoving(true)}>Delete observation</Action>:<Action type="submit" disabled={busy}>{busy?<Busy/>:"Save observation"}</Action>}</div></form>;
}
