import {claimState,hostingReady,type PresenceState} from "./presence";
import type {SpaceState} from "./types";
export type ReadinessCheck={id:string;label:string;status:"ready"|"attention"|"not_checked"|"optional";detail:string};
export function publicationReadiness(state:SpaceState,data:PresenceState,now=Date.now()):ReadinessCheck[]{
  const release=state.releases.find(r=>r.id===state.space.active_release_id),published=Boolean(state.space.active_release_id);
  let official="";try{official=new URL(data.publisher.official_url).hostname;}catch{/* No public identity yet. */}
  const proof=data.claims.some(c=>c.domain===official&&claimState(c,now)==="verified");
  const delivery=data.delivery_checks?.find(c=>c.release_id===state.space.active_release_id),freshDelivery=Boolean(delivery&&now-Date.parse(delivery.created_at)<86400000);
  const resources=data.resource_checks||[],bad=resources.filter(c=>c.status==="failed"||c.result?.ok===false||c.result?.warning),unchecked=resources.filter(c=>!c.checked_at||now-Date.parse(c.checked_at)>86400000||["queued","running"].includes(c.status));
  const changes=data.changes.filter(c=>!release||Date.parse(c.created_at)>Date.parse(release.published_at)),monitorFailures=data.monitors.filter(m=>m.cadence!=="off"&&m.error_message);
  const scheduled=data.monitors.filter(m=>m.cadence!=="off"),pendingSources=scheduled.filter(m=>!m.last_checked_at||now-Date.parse(m.last_checked_at)>(m.cadence==="weekly"?8:2)*86400000);
  const submission=data.discovery?.indexnow_enabled?data.submissions?.find(s=>s.release_id===state.space.active_release_id):undefined;
  const index=data.semantic?.indexes.find(i=>i.release_id===state.space.active_release_id),semanticReady=Boolean(data.semantic?.settings.enabled&&index&&index.total_chunks>0&&index.ready_chunks===index.total_chunks);
  return [
    {id:"identity",label:"Publisher identity",status:proof?"ready":"attention",detail:proof?"The official website has current DNS ownership proof.":"Add your official website and verify control of its exact hostname."},
    {id:"publication",label:"Approved publication",status:published?"ready":"attention",detail:published?"A reviewed release is available through public pages and the API.":"Review and publish your knowledge to make it available to external consumers."},
    {id:"delivery",label:"HTTP and MCP delivery",status:!delivery||!freshDelivery?"not_checked":delivery.result?.passed?"ready":"attention",detail:!delivery?"Run the public delivery check after publishing.":!freshDelivery?"The latest delivery result is over 24 hours old.":delivery.result?.passed?"Current-release HTTP and MCP checks passed.":"The current release has a pending or failed delivery check."},
    {id:"resources",label:"Published resource links",status:!published?"not_checked":bad.length?"attention":unchecked.length?"not_checked":resources.length?"ready":"optional",detail:bad.length?`${bad.length} resource links are unavailable or declare a different format.`:unchecked.length?`${unchecked.length} links need a current availability check.`:resources.length?`${resources.length} published resource links passed their latest availability check.`:"No published resource links to check."},
    {id:"freshness",label:"Source freshness",status:changes.length||monitorFailures.length?"attention":pendingSources.length||!scheduled.length?"not_checked":"ready",detail:changes.length?`${changes.length} source changes were detected after this release; review their effect on published knowledge.`:monitorFailures.length?`${monitorFailures.length} scheduled source checks need attention.`:pendingSources.length?`${pendingSources.length} scheduled sources need an initial or more recent check.`:scheduled.length?"Scheduled monitoring has no recorded failure or later source change. This does not establish every claim's current accuracy.":"Schedule source checks or review content dates manually."},
    {id:"semantic",label:"Semantic retrieval",status:semanticReady?"ready":data.semantic?.settings.enabled?"attention":"optional",detail:semanticReady?"The current release has a complete semantic index. Provider and query limits are checked on each request.":data.semantic?.settings.enabled?"Authorize or finish indexing the current approved release.":"Lexical retrieval is available without an embedding provider."},
    {id:"hosting",label:"Custom hostname",status:hostingReady(data.hosting,now)?"ready":data.hosting?"attention":"optional",detail:hostingReady(data.hosting,now)?"DNS ownership and the HTTPS workspace connection are current.":data.hosting?"Finish the hostname connection or renew its verification.":"Publications can use the application hostname until you connect a domain."},
    {id:"discovery",label:"Search-engine submission",status:submission?.result?.ok?"ready":data.discovery?.indexnow_enabled?"not_checked":"optional",detail:submission?.result?.ok?"IndexNow received a submission for this release. Search inclusion and AI citations still require observation.":data.discovery?.indexnow_enabled?"No successful submission for this release has been recorded yet.":"Use the sitemap and search-console setup; enable IndexNow after connecting your hostname."},
  ];
}
