import "server-only";
export const env={
  UNSITE_SUPABASE_URL:process.env.UNSITE_SUPABASE_URL,
  UNSITE_SUPABASE_PUBLISHABLE_KEY:process.env.UNSITE_SUPABASE_PUBLISHABLE_KEY,
  UNSITE_APP_ORIGIN:process.env.UNSITE_APP_ORIGIN,
  UNSITE_WORKER_TOKEN:process.env.UNSITE_WORKER_TOKEN,
  UNSITE_WORKER_GATEWAY_KEY:process.env.UNSITE_WORKER_GATEWAY_KEY,
};
